"""
The Know Each Other content bank. Seeded directly into ActivityContent
(activity_type="know_each_other") - a fresh, dedicated bank for the new
first-class game, distinct from the legacy classic_question "prediction"
subtype's 25 questions (which remain untouched, still playable through
the old classic flow).

Each entry: prompt (the "answer for yourself" phrasing), predict_text
(the "guess your partner" phrasing), question_type (multiple_choice or
rating), options (the shared choice list both the real answer and the
prediction are drawn from).
"""

RATING_1_10 = [str(i) for i in range(1, 11)]

KNOW_EACH_OTHER_QUESTIONS = []

# --------------------------------------------------------- Multiple choice
KNOW_EACH_OTHER_QUESTIONS += [
    {"prompt": "What's your ideal way to spend a rainy day?",
     "predict_text": "What do you think your partner's ideal rainy day looks like?",
     "question_type": "multiple_choice",
     "options": ["Reading", "Watching movies", "Baking something", "Napping", "Journaling or planning"]},
    {"prompt": "Which would you choose for dessert?",
     "predict_text": "What do you think your partner would choose for dessert?",
     "question_type": "multiple_choice",
     "options": ["Chocolate anything", "Something fruity", "Ice cream", "Cheesecake", "I'll skip dessert"]},
    {"prompt": "What's your go-to order at a coffee shop?",
     "predict_text": "What do you think your partner's go-to coffee order is?",
     "question_type": "multiple_choice",
     "options": ["Black coffee", "A latte or cappuccino", "Tea", "Something iced and sweet", "I don't really drink coffee"]},
    {"prompt": "Which pet would you rather have?",
     "predict_text": "Which pet do you think your partner would choose?",
     "question_type": "multiple_choice",
     "options": ["Dog", "Cat", "Fish", "Bird", "No pets"]},
    {"prompt": "What's your preferred vacation pace?",
     "predict_text": "What do you think your partner's preferred vacation pace is?",
     "question_type": "multiple_choice",
     "options": ["Packed itinerary, see everything", "Slow and relaxed", "A mix of both", "Wherever the day takes us"]},
    {"prompt": "Which app do you spend the most time on?",
     "predict_text": "Which app do you think your partner spends the most time on?",
     "question_type": "multiple_choice",
     "options": ["Instagram", "TikTok", "YouTube", "Messages", "Something else entirely"]},
    {"prompt": "What's your favourite way to exercise?",
     "predict_text": "What do you think your partner's favourite way to exercise is?",
     "question_type": "multiple_choice",
     "options": ["Gym", "Running or walking", "A sport", "Yoga or stretching", "Exercise isn't my thing"]},
    {"prompt": "Which holiday do you enjoy most?",
     "predict_text": "Which holiday do you think your partner enjoys most?",
     "question_type": "multiple_choice",
     "options": ["New Year's", "A birthday", "A big family holiday", "Any long weekend"]},
    {"prompt": "What's your comfort TV genre?",
     "predict_text": "What do you think your partner's comfort TV genre is?",
     "question_type": "multiple_choice",
     "options": ["Sitcoms", "Reality TV", "True crime", "Fantasy or sci-fi", "Documentaries"]},
    {"prompt": "How do you prefer to receive good news?",
     "predict_text": "How do you think your partner prefers to receive good news?",
     "question_type": "multiple_choice",
     "options": ["In person", "A phone call", "A text right away", "Told slowly, with buildup"]},
    {"prompt": "What's your ideal weekend morning?",
     "predict_text": "What do you think your partner's ideal weekend morning is?",
     "question_type": "multiple_choice",
     "options": ["Early workout", "Slow coffee in bed", "Errands, get it done", "Sleeping in"]},
    {"prompt": "Which season fits your personality best?",
     "predict_text": "Which season do you think fits your partner's personality best?",
     "question_type": "multiple_choice",
     "options": ["Spring", "Summer", "Autumn", "Winter"]},
    {"prompt": "What's your snack of choice at the movies?",
     "predict_text": "What do you think your partner's movie snack of choice is?",
     "question_type": "multiple_choice",
     "options": ["Popcorn", "Candy", "Nachos", "I don't snack at movies"]},
    {"prompt": "What's your ideal music for a road trip?",
     "predict_text": "What do you think your partner's ideal road trip music is?",
     "question_type": "multiple_choice",
     "options": ["Whatever's on the radio", "A pre-made playlist", "Podcasts, not music", "Silence, actually"]},
    {"prompt": "How do you like to celebrate a big win?",
     "predict_text": "How do you think your partner likes to celebrate a big win?",
     "question_type": "multiple_choice",
     "options": ["A night out", "A quiet dinner together", "Treating yourself to something", "Calling everyone you know"]},
    {"prompt": "What's your preferred way to learn something new?",
     "predict_text": "What do you think your partner's preferred way to learn is?",
     "question_type": "multiple_choice",
     "options": ["Watching a video", "Reading about it", "Just trying it hands-on", "Having someone show me"]},
    {"prompt": "Which would you rather binge?",
     "predict_text": "Which do you think your partner would rather binge?",
     "question_type": "multiple_choice",
     "options": ["A drama series", "A comedy series", "A documentary series", "A reality show"]},
    {"prompt": "What's your instinct when plans suddenly change?",
     "predict_text": "What do you think your partner's instinct is when plans suddenly change?",
     "question_type": "multiple_choice",
     "options": ["Roll with it", "Feel a bit thrown off", "Try to fix/replan immediately", "Secretly relieved"]},
    {"prompt": "What's your ideal date night budget vibe?",
     "predict_text": "What do you think your partner's ideal date night budget vibe is?",
     "question_type": "multiple_choice",
     "options": ["Free or cheap and fun", "Mid-range and comfortable", "Splash out occasionally", "Money's no object tonight"]},
    {"prompt": "Which chore do you mind least?",
     "predict_text": "Which chore do you think your partner minds least?",
     "question_type": "multiple_choice",
     "options": ["Cooking", "Cleaning", "Laundry", "Errands/shopping"]},
    {"prompt": "What's your favourite kind of surprise?",
     "predict_text": "What do you think your partner's favourite kind of surprise is?",
     "question_type": "multiple_choice",
     "options": ["A small thoughtful gift", "A planned trip", "A party", "Being told, not surprised at all"]},
    {"prompt": "How do you prefer conflict to be resolved?",
     "predict_text": "How do you think your partner prefers conflict to be resolved?",
     "question_type": "multiple_choice",
     "options": ["Talk it out right away", "Cool off first, then talk", "Write it down first", "Humor to break tension"]},
    {"prompt": "What's your go-to comfort activity when stressed?",
     "predict_text": "What do you think your partner's go-to comfort activity is when stressed?",
     "question_type": "multiple_choice",
     "options": ["Exercise", "Talking to someone", "Alone time", "Distraction (TV, games, etc.)"]},
    {"prompt": "Which would you rather have on a lazy Sunday?",
     "predict_text": "What do you think your partner would rather have on a lazy Sunday?",
     "question_type": "multiple_choice",
     "options": ["A big brunch", "Snacks all day", "One proper meal", "Whatever's easiest"]},
]

# ------------------------------------------------------------------ Rating
KNOW_EACH_OTHER_QUESTIONS += [
    {"prompt": "How much do you enjoy surprises?",
     "predict_text": "How much do you think your partner enjoys surprises?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How important is alone time to you in a typical week?",
     "predict_text": "How important do you think alone time is to your partner in a typical week?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy trying new restaurants?",
     "predict_text": "How much do you think your partner enjoys trying new restaurants?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How competitive are you about board games?",
     "predict_text": "How competitive do you think your partner is about board games?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy hosting people at home?",
     "predict_text": "How much do you think your partner enjoys hosting people at home?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How important is punctuality to you?",
     "predict_text": "How important do you think punctuality is to your partner?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy spontaneous plans?",
     "predict_text": "How much do you think your partner enjoys spontaneous plans?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you like public displays of affection?",
     "predict_text": "How much do you think your partner likes public displays of affection?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy deep late-night conversations?",
     "predict_text": "How much do you think your partner enjoys deep late-night conversations?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy travelling somewhere you've never been?",
     "predict_text": "How much do you think your partner enjoys travelling somewhere new?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you like being the center of attention?",
     "predict_text": "How much do you think your partner likes being the center of attention?",
     "question_type": "rating", "options": RATING_1_10},
    {"prompt": "How much do you enjoy a lazy do-nothing day?",
     "predict_text": "How much do you think your partner enjoys a lazy do-nothing day?",
     "question_type": "rating", "options": RATING_1_10},
]
