"""
The initial question bank. Kept as plain data (not hardcoded into templates
or route code) so more questions can be added later just by editing this
list and re-running `python seed/seed.py` - see section 41/42 of the brief.

Each entry is a dict. Defaults are filled in by seed.py:
    text            (required)
    category        (required) one of app.models.question.CATEGORIES
    qtype           (required) one of app.models.question.QUESTION_TYPES
    options         (optional) list[str] - required for multiple_choice,
                    rating, structured_scale, and prediction
    predict_text    (optional) only for qtype == "prediction"
    spicy_level     (optional) 1/2/3, only for category == "spicy"
    match_eligible  (optional) bool, only meaningful for spicy structured_scale
"""

from app.models.question import INTEREST_SCALE

RATING_1_10 = [str(i) for i in range(1, 11)]

QUESTIONS = []

# ---------------------------------------------------------------- Relationship
QUESTIONS += [
    {"text": "What's your favourite memory of us so far?", "category": "relationship", "qtype": "free_text"},
    {"text": "What do I do that makes you feel most loved?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something about our relationship you're proud of?", "category": "relationship", "qtype": "free_text"},
    {"text": "When did you first realise you were falling for me?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something we should do more often?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a small thing I do that means more to you than I probably realise?", "category": "relationship", "qtype": "free_text"},
    {"text": "How do you like to be comforted when you're having a hard day?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a habit of mine you've grown to love?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something you've learned about love from being with me?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's your favourite way for us to spend a lazy day?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's one thing that's gotten better about us over time?", "category": "relationship", "qtype": "free_text"},
    {"text": "How do you know when I'm stressed, even if I don't say anything?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a tradition (big or small) you'd like us to start?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something I do that always makes you smile?", "category": "relationship", "qtype": "free_text"},
    {"text": "How important is it to you that we say 'I love you' often?", "category": "relationship", "qtype": "rating", "options": RATING_1_10},
    {"text": "What's your love language, and do you think I speak it well?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something you appreciate about how we handle disagreements?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a compliment you wish I gave you more often?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's the most 'us' thing we do together?", "category": "relationship", "qtype": "free_text"},
    {"text": "How do you like to be supported when you're chasing a big goal?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something you've never told me about why you love me?", "category": "relationship", "qtype": "free_text"},
    {"text": "On a scale of 1-10, how good are we at communicating right now?", "category": "relationship", "qtype": "rating", "options": RATING_1_10},
    {"text": "What's a moment you felt closest to me recently?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something I could do to make an ordinary day feel special?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a strength of mine you rely on in our relationship?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's something you want me to know you're grateful for?", "category": "relationship", "qtype": "free_text"},
    {"text": "How do you like to celebrate the small wins in our relationship?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's a nickname or inside joke of ours that always makes you laugh?", "category": "relationship", "qtype": "free_text"},
    {"text": "What does 'home' mean to you when you think of us?", "category": "relationship", "qtype": "free_text"},
    {"text": "What's one thing you never want to change about us?", "category": "relationship", "qtype": "free_text"},
]

# --------------------------------------------------------- How Well Do You Know Me
QUESTIONS += [
    {"text": "What's your idea of the perfect night in?", "category": "know_me", "qtype": "prediction",
     "options": ["Movie & takeout", "Cooking together", "Board games or a puzzle", "Just talking for hours", "Curled up with a book each"],
     "predict_text": "What do you think your partner would pick as the perfect night in?"},
    {"text": "If we had a free Saturday with no plans, what would you want to do?", "category": "know_me", "qtype": "prediction",
     "options": ["Sleep in and do nothing", "Go on a spontaneous adventure", "Get productive around the house", "See friends", "Have a whole day just for us"],
     "predict_text": "What do you think your partner would want to do with a free Saturday?"},
    {"text": "What's your go-to comfort food?", "category": "know_me", "qtype": "prediction",
     "options": ["Pizza", "Pasta", "Ice cream", "Something spicy", "Baked goods"],
     "predict_text": "What do you think your partner's comfort food is?"},
    {"text": "Which of these describes your ideal holiday?", "category": "know_me", "qtype": "prediction",
     "options": ["Beach relaxation", "City exploring", "Mountains & hiking", "Road trip", "Somewhere cosy and remote"],
     "predict_text": "What would your partner choose for the perfect holiday?"},
    {"text": "What's your biggest love language?", "category": "know_me", "qtype": "prediction",
     "options": ["Words of affirmation", "Quality time", "Physical touch", "Acts of service", "Gifts"],
     "predict_text": "Which love language do you think matters most to your partner?"},
    {"text": "If you could instantly master one skill, what would it be?", "category": "know_me", "qtype": "prediction",
     "options": ["Cooking", "A musical instrument", "A new language", "Painting or drawing", "Dancing"],
     "predict_text": "What skill do you think your partner would want to instantly master?"},
    {"text": "What's your favourite season?", "category": "know_me", "qtype": "prediction",
     "options": ["Spring", "Summer", "Autumn", "Winter"],
     "predict_text": "What's your partner's favourite season?"},
    {"text": "How do you prefer to spend a birthday?", "category": "know_me", "qtype": "prediction",
     "options": ["A big party", "A quiet dinner for two", "A weekend away", "Surrounded by family", "Something low-key at home"],
     "predict_text": "How do you think your partner prefers to spend their birthday?"},
    {"text": "What's your biggest pet peeve?", "category": "know_me", "qtype": "prediction",
     "options": ["Being late", "Loud chewing", "Leaving lights on", "Messy spaces", "Interrupting"],
     "predict_text": "What do you think is your partner's biggest pet peeve?"},
    {"text": "What's your ideal way to unwind after a hard day?", "category": "know_me", "qtype": "prediction",
     "options": ["Exercise", "Watching something", "Talking it out", "Being alone for a bit", "Music"],
     "predict_text": "How do you think your partner unwinds after a hard day?"},
    {"text": "Which would you pick for a date night?", "category": "know_me", "qtype": "prediction",
     "options": ["Fancy dinner out", "Cooking together at home", "A concert or show", "An outdoor activity", "Something new and unexpected"],
     "predict_text": "What would your partner pick for date night?"},
    {"text": "What's more you: mornings or nights?", "category": "know_me", "qtype": "prediction",
     "options": ["Definitely mornings", "Definitely nights", "A bit of both", "Neither, honestly"],
     "predict_text": "Is your partner more of a morning or night person?"},
    {"text": "What's your dream pet, if you could have any?", "category": "know_me", "qtype": "prediction",
     "options": ["Dog", "Cat", "Something exotic", "No pets, thanks", "All of the above"],
     "predict_text": "What pet do you think your partner secretly wants?"},
    {"text": "Which superpower would you choose?", "category": "know_me", "qtype": "prediction",
     "options": ["Flying", "Reading minds", "Time travel", "Invisibility", "Teleportation"],
     "predict_text": "Which superpower do you think your partner would choose?"},
    {"text": "What's your ideal home vibe?", "category": "know_me", "qtype": "prediction",
     "options": ["Minimalist and calm", "Cosy, full of memories", "Modern and sleek", "Full of plants", "Somewhere with a great view"],
     "predict_text": "What home vibe do you think your partner is drawn to?"},
    {"text": "Which would you rather give up for a year?", "category": "know_me", "qtype": "prediction",
     "options": ["Coffee", "Social media", "Sweets", "Music", "Streaming shows"],
     "predict_text": "What do you think your partner would rather give up for a year?"},
    {"text": "What's your go-to karaoke song style?", "category": "know_me", "qtype": "prediction",
     "options": ["A power ballad", "Something upbeat and fun", "A duet", "I'd refuse to sing", "A song from my teenage years"],
     "predict_text": "What kind of song do you think your partner would pick for karaoke?"},
    {"text": "What's your biggest source of day-to-day stress?", "category": "know_me", "qtype": "prediction",
     "options": ["Work or study", "Money", "Time management", "Family stuff", "Overthinking"],
     "predict_text": "What do you think stresses your partner out the most day-to-day?"},
    {"text": "What kind of movie do you reach for most?", "category": "know_me", "qtype": "prediction",
     "options": ["Comedy", "Romance", "Action or thriller", "Horror", "Documentary"],
     "predict_text": "What genre do you think your partner reaches for most?"},
    {"text": "How do you like to be woken up?", "category": "know_me", "qtype": "prediction",
     "options": ["Gently, time to wake slowly", "Straight to coffee, no talking", "With music", "Cuddles first", "Honestly, don't wake me"],
     "predict_text": "How do you think your partner likes to be woken up?"},
    {"text": "What's your ideal way to work through an argument?", "category": "know_me", "qtype": "prediction",
     "options": ["Talk it out immediately", "Take space first, then talk", "Write it out before speaking", "Humour to break the tension", "A mix of all of these"],
     "predict_text": "How do you think your partner prefers to work through an argument?"},
    {"text": "What's your dream 'someday' purchase?", "category": "know_me", "qtype": "prediction",
     "options": ["A house", "A big trip", "A car", "Something creative", "I'd rather save it"],
     "predict_text": "What do you think your partner's dream someday purchase is?"},
    {"text": "What show or movie do you always rewatch for comfort?", "category": "know_me", "qtype": "prediction",
     "options": ["A sitcom", "A childhood favourite", "One specific movie on repeat", "I don't really rewatch things", "Something with you specifically"],
     "predict_text": "What do you think your partner rewatches for comfort?"},
    {"text": "Which best describes your ideal Sunday?", "category": "know_me", "qtype": "prediction",
     "options": ["Slow mornings, no alarms", "Get things done early, then relax", "Outdoors for most of the day", "Social, seeing people", "A mix of chores and rest"],
     "predict_text": "What does your partner's ideal Sunday look like?"},
    {"text": "What's the first thing you'd do with unexpected free time?", "category": "know_me", "qtype": "prediction",
     "options": ["Nap", "Call you", "Get creative", "Catch up on a show", "Go outside"],
     "predict_text": "What do you think your partner would do first with unexpected free time?"},
]

# ------------------------------------------------------------------- Future
QUESTIONS += [
    {"text": "Where would you love for us to travel together?", "category": "future", "qtype": "free_text"},
    {"text": "What would our ideal home look like?", "category": "future", "qtype": "free_text"},
    {"text": "What do you hope we're doing in five years?", "category": "future", "qtype": "free_text"},
    {"text": "What's one experience you definitely want us to share?", "category": "future", "qtype": "free_text"},
    {"text": "What's a skill you'd love for us to learn together?", "category": "future", "qtype": "free_text"},
    {"text": "What's something you hope never changes about us, even years from now?", "category": "future", "qtype": "free_text"},
    {"text": "What's a tradition you'd want to build together over time?", "category": "future", "qtype": "free_text"},
    {"text": "If we could live anywhere for a year, where would you choose?", "category": "future", "qtype": "free_text"},
    {"text": "What's a goal of yours that you'd love my support with?", "category": "future", "qtype": "free_text"},
    {"text": "What does your ideal future weekend routine with me look like?", "category": "future", "qtype": "free_text"},
    {"text": "What's something you're looking forward to doing together this year?", "category": "future", "qtype": "free_text"},
    {"text": "What kind of home do you picture us in one day - city, countryside, somewhere else?", "category": "future", "qtype": "free_text"},
    {"text": "What's a big adventure you want us to have before we're too old for it?", "category": "future", "qtype": "free_text"},
    {"text": "What's something on your bucket list you'd only want to do with me?", "category": "future", "qtype": "free_text"},
    {"text": "How do you imagine us celebrating a big milestone, like an anniversary?", "category": "future", "qtype": "free_text"},
    {"text": "What's a value you hope we always build our future around?", "category": "future", "qtype": "free_text"},
    {"text": "What's something about getting older together that excites you?", "category": "future", "qtype": "free_text"},
    {"text": "What's a project you'd love us to take on together someday?", "category": "future", "qtype": "free_text"},
    {"text": "What's one way you'd like us to grow, individually, over the next few years?", "category": "future", "qtype": "free_text"},
    {"text": "How important is it to you that we plan things out versus stay spontaneous?", "category": "future", "qtype": "rating", "options": RATING_1_10},
]

# --------------------------------------------------------------- Random/Funny
QUESTIONS += [
    {"text": "If I were an animal, what would I be?", "category": "random", "qtype": "free_text"},
    {"text": "Which one of us would survive longer in a zombie apocalypse?", "category": "random", "qtype": "multiple_choice",
     "options": ["Definitely me", "Definitely you", "We'd survive together or not at all", "Neither of us, let's be honest"]},
    {"text": "If we started a business together, what would we sell?", "category": "random", "qtype": "free_text"},
    {"text": "What's the dumbest thing we've ever argued about?", "category": "random", "qtype": "free_text"},
    {"text": "If our relationship were a movie genre, what would it be?", "category": "random", "qtype": "multiple_choice",
     "options": ["Romantic comedy", "Buddy adventure", "Slow-burn drama", "Action movie", "A mockumentary, honestly"]},
    {"text": "What's the weirdest food combination you actually enjoy?", "category": "random", "qtype": "free_text"},
    {"text": "If you had to describe me as a weather forecast, what would it be?", "category": "random", "qtype": "free_text"},
    {"text": "What's a completely useless talent you have?", "category": "random", "qtype": "free_text"},
    {"text": "If we swapped bodies for a day, what's the first thing you'd do?", "category": "random", "qtype": "free_text"},
    {"text": "What's the most ridiculous thing you've caught yourself doing when you thought no one was watching?", "category": "random", "qtype": "free_text"},
    {"text": "Which fictional couple do we remind you of most?", "category": "random", "qtype": "free_text"},
    {"text": "If our relationship had a theme song, what genre would it be?", "category": "random", "qtype": "multiple_choice",
     "options": ["Pop anthem", "Slow romantic ballad", "Something chaotic and upbeat", "A duet", "An epic movie score"]},
    {"text": "What's the most 'you' thing you've ever done?", "category": "random", "qtype": "free_text"},
    {"text": "If you could give past-you one piece of relationship advice, what would it be?", "category": "random", "qtype": "free_text"},
    {"text": "What's a food you refuse to compromise on when we're deciding what to eat?", "category": "random", "qtype": "free_text"},
    {"text": "If we were cast in a sitcom, what would the show be called?", "category": "random", "qtype": "free_text"},
    {"text": "What's something small that always makes you laugh, no matter how many times it happens?", "category": "random", "qtype": "free_text"},
    {"text": "If you had to pick a mascot for our relationship, what would it be?", "category": "random", "qtype": "free_text"},
    {"text": "What's the most chaotic plan we've ever actually pulled off?", "category": "random", "qtype": "free_text"},
    {"text": "On a scale of 1-10, how competitive are you when we play games together?", "category": "random", "qtype": "rating", "options": RATING_1_10},
]

# ----------------------------------------------------------------------- Deep
QUESTIONS += [
    {"text": "What's something you're afraid to lose?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you've changed your mind about since we started dating?", "category": "deep", "qtype": "free_text"},
    {"text": "What do you think makes a relationship last?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you wish people understood about you?", "category": "deep", "qtype": "free_text"},
    {"text": "What's a fear you've never fully told me about?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something from your childhood that still shapes how you love people?", "category": "deep", "qtype": "free_text"},
    {"text": "What does being truly understood feel like to you?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you're still learning to forgive yourself for?", "category": "deep", "qtype": "free_text"},
    {"text": "What's a belief about love you held before us that's changed?", "category": "deep", "qtype": "free_text"},
    {"text": "What does emotional safety look like to you in a relationship?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you need more of from the people who love you?", "category": "deep", "qtype": "free_text"},
    {"text": "What's a moment that quietly changed who you are?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you're proud of that you rarely get credit for?", "category": "deep", "qtype": "free_text"},
    {"text": "What does it mean to you to be truly known by someone?", "category": "deep", "qtype": "free_text"},
    {"text": "What's a part of yourself you're still working on accepting?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something you wish you'd learned earlier about relationships?", "category": "deep", "qtype": "free_text"},
    {"text": "How do you personally define happiness right now in your life?", "category": "deep", "qtype": "free_text"},
    {"text": "What's a value you'd never compromise on, even for love?", "category": "deep", "qtype": "free_text"},
    {"text": "What's something difficult you've grown from in the past year?", "category": "deep", "qtype": "free_text"},
    {"text": "How do you want to be remembered by the people closest to you?", "category": "deep", "qtype": "free_text"},
]

# ------------------------------------------------------------------ Memories
QUESTIONS += [
    {"text": "What do you remember most about our first date?", "category": "memories", "qtype": "free_text"},
    {"text": "What's one trip together you'll never forget?", "category": "memories", "qtype": "free_text"},
    {"text": "What was your funniest moment together?", "category": "memories", "qtype": "free_text"},
    {"text": "What's the first thing you noticed about me?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a memory of us that always makes you smile when you think of it?", "category": "memories", "qtype": "free_text"},
    {"text": "What's the most 'we really did that' moment we've shared?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a small, ordinary moment with me that stuck with you?", "category": "memories", "qtype": "free_text"},
    {"text": "What's your favourite photo of us, and why?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a meal or restaurant that holds a special memory for us?", "category": "memories", "qtype": "free_text"},
    {"text": "What's the first gift I gave you that you remember?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a memory from early on that told you this could be something real?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a moment we got through something hard together that you're proud of?", "category": "memories", "qtype": "free_text"},
    {"text": "What's the silliest inside joke that started from a real memory?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a memory of us that you'd want to relive exactly as it happened?", "category": "memories", "qtype": "free_text"},
    {"text": "What's a moment when you knew you could just be fully yourself with me?", "category": "memories", "qtype": "free_text"},
]

# ------------------------------------------------------------- Long Distance
QUESTIONS += [
    {"text": "What's something you wish we could do together right now?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's the first thing you want to do when we're together again?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What part of our calls do you look forward to most?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's something we could start doing together despite the distance?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's the hardest part of being apart for you right now?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's something small you do that makes the distance feel a little smaller?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's a way I can support you better while we're apart?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What do you miss most about being in the same room as me?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's something you look forward to about the next time we see each other?", "category": "longdistance", "qtype": "free_text"},
    {"text": "How do you like to stay connected on a day when we can't talk much?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's something about long distance that's surprised you, good or bad?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's a way we could 'do' something together virtually that we haven't tried yet?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's a countdown or goal that's helping you get through the distance?", "category": "longdistance", "qtype": "free_text"},
    {"text": "What's something you've learned about yourself from being in a long-distance relationship?", "category": "longdistance", "qtype": "free_text"},
    {"text": "On a scale of 1-10, how are you really feeling about the distance lately?", "category": "longdistance", "qtype": "rating", "options": RATING_1_10},
]

# ------------------------------------------------------------------- Spicy 🌶️
# Optional, disabled by default, requires both partners to opt in
# independently (see app/routes/settings.py + services/privacy.spicy_unlocked).
# Explicit and sex-focused by design once both partners have confirmed
# they're adults and both opted in - this bank exists so a couple can
# actually discuss and calibrate real preferences, not just euphemisms.
# Tier 3 ("Adventurous") deliberately names specific acts/kinks (anal, toys,
# restraints/bondage, filming, power play, etc. - not an exhaustive list)
# so structured_scale answers feed a genuinely useful "Find your matches"
# view rather than staying vague.

# 🌶️ Flirty
QUESTIONS += [
    {"text": "What was your first real 'butterflies' moment with me?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's something I do without realising that you find really attractive?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What outfit of mine do you secretly love the most?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's your favourite way for us to flirt with each other?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's a compliment about your looks you'd love to hear from me more?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Where's your favourite place for me to kiss you?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Forehead", "Cheek", "Neck", "Lips", "Hands"]},
    {"text": "What's a moment our chemistry felt undeniable to you?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's something about the way we look at each other that you love?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Do you prefer slow-burn tension or getting straight to the point?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Slow burn, all the way", "A bit of both", "Straight to the point", "Depends on my mood"]},
    {"text": "What's a small, everyday moment that turns you on more than people would expect?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's your love language when it comes to physical affection specifically?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's a way I could surprise you that would make you blush?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
]

# 🌶️🌶️ Intimate - mostly structured_scale so answers can feed "Find your matches"
QUESTIONS += [
    {"text": "Trying a new date-night ritual built around romance and anticipation", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Writing each other a private, intimate letter to read together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Setting aside a phone-free evening focused entirely on each other", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Planning a surprise 'just for us' evening with no explanation beforehand", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Talking more openly about what makes each of us feel desired", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a slower, more intentional pace during intimate time together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Exploring a new kind of massage or touch together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Creating a shared 'yes / no / maybe' list to talk through comfort levels", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being more verbal about what feels good in the moment", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying some light roleplay or pretend together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being more spontaneous about intimacy rather than always planning it", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Incorporating more anticipation or teasing before getting intimate", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "What makes you feel most desired by me?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
]

# 🌶️🌶️🌶️ Adventurous
QUESTIONS += [
    {"text": "Exploring a new setting or location together for intimacy (within reason)", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a blindfold or another simple sensory-focused experience", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Incorporating toys or props into intimate time together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a themed night with a costume or roleplay scenario", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Exploring light power-dynamic play, taking turns leading", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a room or spot at home you haven't been intimate in before", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being more spontaneous - initiating intimacy in an unplanned moment", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Exploring light restraint play together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "What's a fantasy you're comfortable sharing that we haven't talked about before?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Trying a 'surprise' day where one partner plans an intimate experience for the other", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying anal sex together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Using a vibrator or other sex toy during sex", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being tied up with real restraints (rope, cuffs, a tie) during sex", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being the one doing the tying, with your partner restrained", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Filming or photographing an intimate moment together, just for the two of us", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying light spanking or impact play", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Taking on a clearly dominant or submissive role for a scene", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Acting out a specific roleplay scenario (strangers, a fantasy setup, etc.)", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Exploring edging or drawn-out orgasm control together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying temperature play - ice, warm massage oil, etc.", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Sending a sexy photo or message to each other in the middle of the day", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Watching porn or reading erotica together for inspiration", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Mutual masturbation, watching each other", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying sex somewhere semi-public but still safe and private (a car, a balcony, etc.)", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A whole session focused only on oral, no other goal", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Combining a blindfold with restraints for a fuller sensory scene", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "What's a specific fantasy - involving anal, toys, restraints, or anything else - you'd want to explore with me?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there something you've seen, read, or watched that turned you on that you'd want to try together?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's a roleplay scenario or power dynamic you'd fantasize about us acting out?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
]

# 🌶️🌶️🌶️ Prediction - guess your partner's real preference, same
# "prediction" mechanic used elsewhere (services/prediction.py), just with
# a spicy-tagged, explicit question bank.
QUESTIONS += [
    {"text": "Which of these are you most curious to try together?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["Anal", "Sex toys", "Bondage or restraints", "Roleplay", "Filming ourselves"],
     "predict_text": "Which do you think your partner is most curious about?"},
    {"text": "What's your ideal pace during sex?", "category": "spicy", "qtype": "prediction", "spicy_level": 2,
     "options": ["Slow and drawn-out", "Fast and intense", "Depends on the mood", "A mix of both"],
     "predict_text": "What pace do you think your partner prefers?"},
    {"text": "Which turns you on more?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["Being in control", "Giving up control", "Switching between both", "Neither, equal footing"],
     "predict_text": "Which do you think your partner picked?"},
    {"text": "What time of day are you most in the mood?", "category": "spicy", "qtype": "prediction", "spicy_level": 1,
     "options": ["Morning", "Afternoon", "Night", "Whenever it happens"],
     "predict_text": "When do you think your partner is most in the mood?"},
    {"text": "Which sounds most appealing right now?", "category": "spicy", "qtype": "prediction", "spicy_level": 2,
     "options": ["A slow massage that leads somewhere", "Something spontaneous and quick", "A planned date night with a toy or two", "Just cuddling and seeing where it goes"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "How do you feel about filming or photographing an intimate moment together?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["Into the whole thing", "Just a few photos, nothing more", "Not for me", "Curious but nervous"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "What's your favourite way to be touched first?", "category": "spicy", "qtype": "prediction", "spicy_level": 2,
     "options": ["Neck or shoulders", "Lower back", "Inner thighs", "Somewhere else entirely"],
     "predict_text": "Where do you think your partner picked?"},
    {"text": "Which sounds like the most fun date-night twist?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["A toy shopping trip together", "A roleplay costume night", "A blindfolded surprise evening", "A no-rules spontaneous night"],
     "predict_text": "What do you think your partner picked?"},
]

# --------------------------------------------------------- Spicy - Expanded Bank
# Added once the original curated set (above) got played through. Same
# rules as everywhere else: category="spicy", gated by spicy_unlocked(),
# excluded from Stats. Deliberately broader in TOPIC (not just more kink
# variety) and broader in FORMAT - more free_text (write-your-own, meant
# to take longer and prompt real conversation) and more multiple_choice
# (quick, both-reveal-independently picks) alongside more
# structured_scale and prediction content.

# --- Comfort Scale (structured_scale) - more specific, wider range -----
QUESTIONS += [
    {"text": "Taking a slow, unhurried bath or shower together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Giving each other a proper massage before anything else happens", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Leaving flirty notes or texts for each other during the day", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Dressing up specifically to catch your partner's eye", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Slow dancing together at home, just the two of us", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying new lingerie or underwear for each other", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Taking a long, unrushed session with no clock in the room", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Slow, drawn-out mutual undressing", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Spending more time on foreplay than usual", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A session focused purely on touch, no penetration at all", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being more vocal about what feels good in the moment", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Starting somewhere other than the bedroom", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Cuddling and talking honestly right afterward", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A slower, more drawn-out build-up before anything else", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Treating kissing as its own focus, not just a lead-in", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a position you haven't explored much together", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying 69", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Incorporating nipple play", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Talking through a threesome fantasy together, just as conversation", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Watching your partner masturbate", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being watched while masturbating", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a rougher, more intense pace for a change", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a gentler, slower pace for a change", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Incorporating light hair-pulling", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Dressing up in a specific costume or character look", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Phone sex or a sexy call when we're apart", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A longer session with multiple rounds in one night", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A 'no talking, just touch' session for a change of pace", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Using ice cubes or something cold during foreplay", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 3, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "A little scavenger-hunt style buildup - small challenges leading to the bedroom", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Picking a specific playlist to set the mood", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being intentionally louder than usual", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Being intentionally quiet, even when it's hard to", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Trying a full weekend morning with absolutely nowhere to be", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 1, "options": INTEREST_SCALE, "match_eligible": True},
    {"text": "Planning an entire evening around intimacy, start to finish", "category": "spicy", "qtype": "structured_scale",
     "spicy_level": 2, "options": INTEREST_SCALE, "match_eligible": True},
]

# --- Fantasy Guess (free_text) - longer, more thoughtful prompts -------
QUESTIONS += [
    {"text": "What's a small gesture during intimacy that always gets you in the mood?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Describe your ideal lazy Sunday morning together, in as much detail as you want.", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What outfit or look of mine do you secretly love the most?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's a compliment about your body you wish I said more often?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's your favourite memory of us being intimate together?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Describe, in detail, what your perfect date night ending would look like.", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's something you've always wanted to say during sex but haven't?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's a fantasy setting - not act, just a place - you'd love for us to be intimate in?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "If you could plan one entire evening for us with no limit on time or effort, what would it look like?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's something you find surprisingly attractive about me that I might not know?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Describe a moment you felt the most desired by me.", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "What's a specific way you like to be praised or reassured during sex?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's something you'd want me to whisper to you in the moment?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What does 'good sex' actually mean to you, in your own words?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's a small thing I do that instantly turns you on?", "category": "spicy", "qtype": "free_text", "spicy_level": 1},
    {"text": "Describe a fantasy scenario, start to finish, that you'd want us to act out together.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's a specific position or act you've been curious about but never brought up?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "If we filmed one thing together, just for us, what would you want it to be?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's the most adventurous thing you'd want to try with me? Describe it.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Describe what an entire 'no rules' night with me would look like for you.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's a specific roleplay character or scenario you'd want to try?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's something you've seen or read that stuck with you, that you'd want to try a version of?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's a fantasy you have that involves a specific location outside the house?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Describe your ideal pace, positions, and mood for a night when we have the whole house to ourselves.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's something about your own body you'd want me to pay more attention to?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's a way you'd want to be surprised intimately that you haven't told me?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "If you could redesign our bedroom purely for intimacy, what would you change?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's a specific thing you'd want to hear me say mid-way through sex?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "Describe a slow, drawn-out scenario where nothing is rushed - what does it look like?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's a fantasy involving control - either giving it up or taking it - that appeals to you?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's something new you'd want to try just once, even if you're not sure it'd become a regular thing?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's a specific piece of clothing - or lack of it - you'd want me to wear?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "Describe the most memorable sex we've ever had, and what made it stand out.", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "What's an unspoken preference you have during sex that I should know?", "category": "spicy", "qtype": "free_text", "spicy_level": 2},
    {"text": "If tonight had zero limits on time or energy, what would you want it to look like?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
]

# --- Quick picks (multiple_choice) - both reveal independently ---------
QUESTIONS += [
    {"text": "Where do you most like to be kissed first?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Neck", "Lips", "Collarbone", "Hands", "Somewhere else"]},
    {"text": "What sets the mood best for you?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Music", "Candlelight", "Total darkness", "Talking first", "No 'setting the mood', just spontaneity"]},
    {"text": "Which do you like best in the moment?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Pet names", "My actual name", "No talking needed"]},
    {"text": "How do you like being woken up in the morning?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["A kiss", "Cuddles first", "Coffee first, then intimacy", "Whatever happens happens"]},
    {"text": "What's your ideal 'setting' for a spontaneous moment?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["The shower", "The kitchen", "The couch", "The car", "Somewhere we've never tried"]},
    {"text": "Which matters more to you in the moment?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Eye contact", "Being close, skin to skin", "What's being said", "The pace"]},
    {"text": "What's your favourite way for things to start?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["A long kiss", "A massage", "Teasing and anticipation", "Straight to it"]},
    {"text": "How do you feel about music during sex?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Love it", "Depends on the song", "Prefer silence", "Haven't thought about it"]},
    {"text": "What matters more to you for a good night?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Emotional connection", "Physical chemistry", "Both equally", "Depends on the night"]},
    {"text": "What's your favourite non-genital spot to be touched?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Neck", "Lower back", "Inner thighs", "Ears", "Somewhere else"]},
    {"text": "How adventurous do you feel this month?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Very - let's try something new", "Somewhat", "Comfort zone is good", "Depends on the day"]},
    {"text": "Which sounds most fun to try this week?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["A new position", "A new location", "A toy", "Roleplay", "Just more time together"]},
    {"text": "What's your pace preference tonight?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Slow and drawn out", "Fast and intense", "Whatever feels right in the moment"]},
    {"text": "Which role appeals to you more right now?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["Leading", "Following", "Switching between both", "Neither, just equal"]},
    {"text": "What's your top pick for a 'just for us' video or photo?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["A few photos", "A short video", "Neither, just memory", "Not sure yet"]},
    {"text": "Which toy sounds most appealing to try or use again?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["A vibrator", "Massage oil or a candle", "Restraints", "A blindfold", "None right now"]},
    {"text": "Where would you want to try being intimate that we haven't?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["A hotel", "Outdoors, somewhere private", "A different room at home", "A road trip stop", "Nowhere new right now"]},
    {"text": "What's your ideal aftercare?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Cuddling and talking", "Quiet closeness", "A shower together", "Falling asleep", "Snacks and chatting"]},
    {"text": "Which turns you on more in the moment?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Being told what to do", "Being asked what you want", "Figuring it out together", "Silence and just doing"]},
    {"text": "What's your favourite kind of foreplay?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Making out", "Massage", "Oral", "Teasing and anticipation", "Dirty talk"]},
    {"text": "How do you feel about trying something totally new tonight?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Yes, let's do it", "Maybe, tell me more first", "Not tonight, another time"]},
    {"text": "How do you like being complimented in the moment?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["About how I look", "About how I make you feel", "About specific things I do", "I don't need it, just show me"]},
    {"text": "What's your ideal length for tonight?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 2,
     "options": ["Quick and spontaneous", "Medium, unhurried", "Long, multiple rounds", "Depends entirely on the day"]},
    {"text": "Which appeals to you most as a fantasy theme?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["Strangers, first time again", "A specific character or costume", "Just us, more intense", "Somewhere risky but safe"]},
    {"text": "What's your favourite way to end the night?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Falling asleep tangled up", "A shower together", "Talking for a while first", "Straight to sleep, no talking needed"]},
    {"text": "How do you feel about trying anal?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["Very open to it", "Curious but nervous", "Not for me", "We've tried it and I liked it"]},
    {"text": "How do you feel about incorporating toys?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3,
     "options": ["Love the idea", "Open to trying", "Prefer without", "We already use them and love it"]},
    {"text": "What's your favourite time of day for intimacy?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 1,
     "options": ["Morning", "Afternoon", "Night", "Whenever it happens"]},
]

# --- Guess your partner (prediction) - wider range of topics -----------
QUESTIONS += [
    {"text": "What's your ideal foreplay length?", "category": "spicy", "qtype": "prediction", "spicy_level": 2,
     "options": ["Just a few minutes", "10-15 minutes", "As long as possible", "Depends on the mood"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "Which matters more to you?", "category": "spicy", "qtype": "prediction", "spicy_level": 1,
     "options": ["Quality over frequency", "Frequency over quality", "Both equally", "Whatever happens happens"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "What's your favourite way to be complimented during sex?", "category": "spicy", "qtype": "prediction", "spicy_level": 1,
     "options": ["About my body", "About how I make you feel", "About specific things I do", "I don't need it"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "Which sounds more like you tonight?", "category": "spicy", "qtype": "prediction", "spicy_level": 2,
     "options": ["Fast and intense", "Slow and drawn out", "Playful and teasing", "Whatever happens"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "What's your go-to way to initiate?", "category": "spicy", "qtype": "prediction", "spicy_level": 1,
     "options": ["A look", "A touch", "Saying it outright", "Setting the mood first"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "Which appeals to you more as a fantasy?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["Being pursued", "Doing the pursuing", "Mutual and equal", "Depends on my mood"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "What's your favourite non-sexual lead-up?", "category": "spicy", "qtype": "prediction", "spicy_level": 1,
     "options": ["A shared shower", "A massage", "Just talking closely", "A slow dance"],
     "predict_text": "What do you think your partner picked?"},
    {"text": "How do you feel about trying bondage or restraints?", "category": "spicy", "qtype": "prediction", "spicy_level": 3,
     "options": ["Very into it", "Curious", "Prefer without", "We already do and I love it"],
     "predict_text": "What do you think your partner picked?"},
]

# --------------------------------------------------------- Spicy - Advanced/Specific Expansion
# For couples who've already covered the basics (anal, rough sex, bondage,
# oil, vibrators are assumed prior experience, not new territory). These
# skip "would you try X" / interest-scale framing entirely - that's covered
# above - and instead ask which specific variant, implement, position, or
# detail they actually want next. spicy_level 3 throughout. Deliberately
# mixes multiple_choice and free_text, and the entries below are randomly
# interleaved on purpose (not grouped by sub-topic) so anal/bondage/toy/
# rough-sex questions don't all land back-to-back when browsing or drawing
# randomly from the category.
QUESTIONS += [
    {"text": "Is there a specific toy - name the type - you want us to buy that we don't already own? What would you want it used for?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there anal play you've fantasised about that isn't full anal sex - a butt plug, prostate stimulation, a toy? Describe exactly what you want.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Predicament bondage - where staying still takes real effort - or just simple restraint?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Predicament, I want the challenge", "Simple restraint is plenty", "Depends on my mood that night", "Never tried it, but curious"]},
    {"text": "Is there a position or angle for anal you've thought about but never asked for? Walk me through exactly what you want.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "What's the difference for you between anal that's slow and intimate versus anal that's rough and intense - which are you craving right now?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Which vibrator style do you actually want more of?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A bullet vibrator - precise and small", "A wand vibrator - broad and intense", "A rabbit vibrator - internal and external at once", "A remote-control one I can wear out"]},
    {"text": "If you could combine three specifics from anal, bondage, and toys into one scene, what would it look like start to finish?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "For anal, which toy do you want in rotation?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A small starter butt plug", "A vibrating butt plug", "Anal beads", "A prostate massager"]},
    {"text": "What's a bondage scenario you've thought about that combines restraint with something else - blindfold, temperature play, a toy? Describe the whole thing.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there a specific piece of gear - rope, cuffs, a spreader bar, a gag - you want us to actually buy and use? Which one, and why that one?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there a specific way you want fingers used during anal play - how many, what motion, how much pressure? Be specific.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Which matters more with toys - who's holding it, or having your hands free to use it yourself?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["I want you holding and controlling it", "I want to be the one holding it", "Hands-free (worn), so both of us are free", "Depends entirely on the toy"]},
    {"text": "Is there specific dirty talk or degradation you want during rough sex that you haven't told me the exact words for? Write them out.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "For light restraint, what's your go-to?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A tie or scarf on the wrists", "Furry cuffs", "Just my hands pinning yours, no props", "One hand restrained, one free"]},
    {"text": "How do you want the pace to build during rough sex?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Rough from the very first thrust", "Slow start that builds to rough", "Rough, then slows right before finishing", "Alternating rough and slow throughout"]},
    {"text": "Is there a specific outfit, position, or angle you'd want on camera that you might not ask for otherwise?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How do you want face slapping paced through a scene?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["One or two, for shock, then done", "Woven throughout as things get rougher", "Only right before you finish", "Not something I want right now"]},
    {"text": "During rough sex, what do you want me saying to you?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Degrading or dirty talk", "Praise, even while it's rough", "Instructions - telling you exactly what to do", "Not much talking, just sounds"]},
    {"text": "Describe exactly how you'd want a toy used on you - which one, where, at what intensity, for how long.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How do you want anal play worked into foreplay rather than saved for later - what order do you want things to happen in?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "If we filmed something, what's the actual setup you'd want?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Phone propped up, wide shot", "Phone handheld, POV", "A mirror we can see ourselves in", "A proper camera on a tripod"]},
    {"text": "What's the difference for you between being tied up as teasing versus being tied up so you genuinely can't move? Which do you want more?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How rough do you want hair-pulling to get?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A light tug, just enough to feel it", "A firm pull that controls the angle of your head", "Hard enough it's the main sensation for a moment", "Not really my thing, skip it"]},
    {"text": "What's your ideal pace once you're inside during anal?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Slow and controlled the whole way", "Slow start, then rough once I've adjusted", "Rough from the first thrust", "Whatever pace you set - I want you to decide"]},
    {"text": "What's the actual line for you between 'rough' and 'too much' - describe it in terms of what you want, not just what to avoid.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "For toys during oral, what do you actually want added?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A vibrator used on me at the same time", "A toy used on you while I go down on you", "No toys, just mouths and hands", "A toy afterward, not during"]},
    {"text": "Do you want marks - bruises, scratches, hickeys - left after rough sex?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Yes, I like seeing them after", "A few, nothing too visible", "Only somewhere clothes will cover", "No marks, just the roughness itself"]},
    {"text": "What's your ideal grip during rough sex?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Wrists pinned above your head", "Hair grabbed and pulled", "Hips gripped hard enough to leave marks", "Jaw held, angling your face toward me"]},
    {"text": "Would you rather be in front of the camera or behind it?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["In front - I want to perform for it", "Behind it - I want to direct", "Both, we take turns", "Neither, but I'd watch it back"]},
    {"text": "Who do you want in control during a rough scene - you directing me, or me fully taking over? Describe what that looks like.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "If we made something just for us, what exact scene would you want captured - position, angle, how long?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Would you want a butt plug in during other acts - like while I go down on you, or during vaginal sex? Describe the scenario.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Which multi-point restraint sounds best to you?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Wrists and ankles both tied, spread out", "Wrists tied to a spreader bar", "Hogtie-style, wrists to ankles", "Just wrists - keep it simple"]},
    {"text": "What's your rule for the footage afterward?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Watch it together right after, then delete", "Keep it in a password-locked file", "Keep it, watch it again sometime", "Delete it immediately - no keeping it"]},
    {"text": "For slapping, are we talking face, ass, or somewhere else?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Face, open palm", "Ass, harder than spanking", "Thighs", "Not face slapping specifically, but ass or thighs yes"]},
    {"text": "If we filmed, would you want to know it's rolling the whole time, or be surprised mid-scene?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Know from the start", "Surprise me partway through", "I'd want to set it up myself", "I wouldn't want to be surprised, but I'm into filming"]},
    {"text": "Which do you want us to try next: a cock ring, nipple clamps, or a feather/tickler?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Cock ring", "Nipple clamps", "Feather or tickler", "None of those specifically"]},
    {"text": "Is there a specific way you want to be talked to during anal - degrading, reassuring, or something else? Give me the actual words.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there a specific check-in system you want for more intense bondage scenes, separate from what we already use day to day?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Where should a remote-control toy actually go on a night out?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Nowhere public, just at home", "Dinner out, low intensity", "A whole evening out, you control it", "Not into wearing one in public at all"]},
    {"text": "What would make anal feel like its own event rather than part of the night - how it starts, how long it lasts, how it ends?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Where do you want to be spanked?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Just the ass", "Ass and upper thighs", "Wherever you decide in the moment", "I'd want to direct exactly where"]},
    {"text": "What would you actually want filmed?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["The whole thing, start to finish", "Just one specific act", "Just audio, no video", "Just photos, not video"]},
    {"text": "What would make you feel sexy on camera rather than self-conscious - lighting, angle, me talking to you, something else?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Which kind of anal play do you want more of right now?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Rimming (oral)", "Fingers", "A butt plug while we do something else", "A small vibrator against the entrance", "Rotate through all of them"]},
    {"text": "Which position do you want next time we do anal?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Doggy, so you can control the depth", "On your back with legs pushed up", "Spooning, slow and close", "Bent over the bed or counter", "Riding, so I control the pace"]},
    {"text": "Is there a toy we already own that you want used differently than we usually use it? How?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "If we used a spreader bar, where would you want it?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Ankles", "Wrists", "Both, on separate occasions", "Not into spreader bars specifically"]},
    {"text": "What's a toy-based scenario you've thought about that we haven't tried - a specific combo of toy plus position plus pace?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Which dildo feature matters more to you?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Size - going bigger than usual", "Texture - ribbed or realistic", "Double-ended, so we can use it on each other", "Doesn't matter - it's about how it's used"]},
    {"text": "Is there a specific moment from something we've already done that you wish had been filmed? Describe it.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How long do you actually want to stay restrained before anything else happens?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A couple minutes of teasing, then get to it", "A long build-up - 15+ minutes restrained", "As long as you can stand it", "However long feels right in the moment"]},
    {"text": "For spanking, what's your preferred implement?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Open hand", "A proper paddle", "A belt", "A flogger (a multi-strand whip)", "Whatever's closest in the moment"]},
    {"text": "If you were the one doing the tying instead of being tied, what would you want to do to me?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How hard do you actually want spanking to go?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Light, more sting than force", "Hard enough my hand tingles after", "Hard enough to mark", "Building from light to hard over the scene"]},
    {"text": "Which butt-plug-size progression sounds better for a night in?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Straight to my usual size", "Small, then build up over the night", "One size, worn the whole evening", "No progression - fingers first, no butt plug"]},
    {"text": "What's the single most explicit request you've never actually said out loud to me? Write it exactly as you'd want it to happen.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How much prep do you actually want before anal, realistically?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A few minutes of fingers is enough", "A proper build-up - rimming and fingers", "Prep with a small butt plug first, then you", "As little as possible, just lots of lube"]},
    {"text": "Describe your ideal full bondage scene - what you're restrained with, for how long, and what happens while you're tied up.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "For rope, what's more appealing - decorative ties, or purely functional restraint?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Decorative - I want it to look good", "Functional - just keep me still", "Start decorative, end functional", "I'd rather use cuffs than rope"]},
    {"text": "Describe a full 'no holding back' night for you - pick specifics from anal, bondage, toys, and roughness, and put them in the order you want them.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Would you want to use a toy on me while I'm using one on you at the same time? Describe how that would work.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Describe your ideal anal scene from the first touch to the finish - how it starts, how rough or slow it gets, and how it ends.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Is there a scenario mixing rough sex and filming you'd want - what's on camera, and how rough does it get?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How deep do you want me pushing during anal?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Just the tip, teasing", "Halfway and steady", "As deep as I can comfortably take", "However deep feels right in the moment - your call"]},
    {"text": "Describe your ideal rough scene - the exact mix of spanking, slapping, pinning, or hair-pulling you want, and how hard each one should be.", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "How long do you want rimming (oral) to last before moving on?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Just enough to get me ready", "A few minutes of proper attention", "As long as you're willing to give", "Until I ask for more"]},
    {"text": "Where do you want to actually be wearing a butt plug?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Just in the bedroom", "Around the house before sex", "Out somewhere, under clothes", "Surprise me with the timing"]},
    {"text": "What's your honest take on rimming (oral sex on you) - what do you want done to you, and what would you want to do to me?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Would you want to watch it back together that same night, or save it for another time? Why?", "category": "spicy", "qtype": "free_text", "spicy_level": 3},
    {"text": "Where do you want to be tied for something light and quick?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Wrists to the headboard", "Wrists behind your back", "Ankles tied together", "Hands pinned above your head, nothing tied"]},
    {"text": "What would you want combined with restraint for a fuller scene?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["A blindfold", "Ear plugs or headphones, for full sensory deprivation", "A gag", "Nothing else - restraint alone is enough"]},
    {"text": "Should I finish inside you during anal, or switch to something else?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Finish inside", "Pull out and finish on me", "Switch to vaginal to finish", "Switch to oral to finish"]},
    {"text": "For anal play, what matters more - the toy's size or its vibration?", "category": "spicy", "qtype": "multiple_choice", "spicy_level": 3, "options": ["Size - I want to feel full", "Vibration - I want the buzz", "Both together", "Neither - just fingers or tongue"]},
]
