"""
The Would You Rather content bank. Seeded directly into ActivityContent
(activity_type="would_you_rather") - there's no legacy-system equivalent
to migrate from, this game only ever exists in the new Activity system.

Each entry: prompt (shown above both options), category (normal/funny/deep),
option_a/option_b (the two choices), and optional emoji_a/emoji_b for a
little visual flair on each option card.
"""

WOULD_YOU_RATHER_QUESTIONS = []

# --------------------------------------------------------------- Normal
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Spend a week on a tropical island", "emoji_a": "🏝️",
     "option_b": "Spend a week in the mountains", "emoji_b": "🏔️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A home-cooked candlelit dinner", "emoji_a": "🍝",
     "option_b": "A fancy night out at a restaurant", "emoji_b": "🥂"},
    {"prompt": "Would you rather go on", "category": "normal",
     "option_a": "A big trip with friends", "emoji_a": "👯",
     "option_b": "A quiet getaway just the two of us", "emoji_b": "💕"},
    {"prompt": "Would you rather we", "category": "normal",
     "option_a": "Wake up early together", "emoji_a": "🌅",
     "option_b": "Sleep in together", "emoji_b": "😴"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A spontaneous surprise trip", "emoji_a": "🎒",
     "option_b": "A carefully planned dream vacation", "emoji_b": "🗺️"},
    {"prompt": "Would you rather live in", "category": "normal",
     "option_a": "The city", "emoji_a": "🏙️",
     "option_b": "The countryside", "emoji_b": "🌾"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A movie night at home", "emoji_a": "🛋️",
     "option_b": "A night out at the cinema", "emoji_b": "🎬"},
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Cook a meal together", "emoji_a": "👩‍🍳",
     "option_b": "Order in and relax", "emoji_b": "🥡"},
    {"prompt": "Would you rather take", "category": "normal",
     "option_a": "A road trip", "emoji_a": "🚗",
     "option_b": "A flight somewhere far away", "emoji_b": "✈️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A big birthday party", "emoji_a": "🎉",
     "option_b": "A quiet birthday just for two", "emoji_b": "🕯️"},
    {"prompt": "Would you rather stay in", "category": "normal",
     "option_a": "A beach house", "emoji_a": "🏖️",
     "option_b": "A cabin in the woods", "emoji_b": "🛖"},
    {"prompt": "Would you rather save up for", "category": "normal",
     "option_a": "A house", "emoji_a": "🏡",
     "option_b": "A year of travel", "emoji_b": "🧳"},
]

# ---------------------------------------------------------------- Funny
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Only communicate in memes for a week", "emoji_a": "😂",
     "option_b": "Only communicate in song lyrics for a week", "emoji_b": "🎤"},
    {"prompt": "Would you rather fight", "category": "funny",
     "option_a": "One horse-sized duck", "emoji_a": "🦆",
     "option_b": "A hundred duck-sized horses", "emoji_b": "🐴"},
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Have to sing instead of talk, forever", "emoji_a": "🎶",
     "option_b": "Have to dance instead of walk, forever", "emoji_b": "💃"},
    {"prompt": "Would you rather never eat", "category": "funny",
     "option_a": "Pizza again", "emoji_a": "🍕",
     "option_b": "Another movie night snack again", "emoji_b": "🍿"},
    {"prompt": "Would you rather be able to talk to", "category": "funny",
     "option_a": "Animals", "emoji_a": "🐶",
     "option_b": "Plants", "emoji_b": "🌱"},
    {"prompt": "Would you rather have to", "category": "funny",
     "option_a": "Wear a costume every day for a month", "emoji_a": "🦸",
     "option_b": "Speak in an accent every day for a month", "emoji_b": "🗣️"},
    {"prompt": "Would you rather time travel to", "category": "funny",
     "option_a": "The past", "emoji_a": "⏪",
     "option_b": "The future", "emoji_b": "⏩"},
    {"prompt": "Would you rather I become a famous", "category": "funny",
     "option_a": "Chef", "emoji_a": "👨‍🍳",
     "option_b": "Musician", "emoji_b": "🎸"},
    {"prompt": "Would you rather have", "category": "funny",
     "option_a": "Unlimited snacks but no naps", "emoji_a": "🍪",
     "option_b": "Unlimited naps but no snacks", "emoji_b": "😴"},
    {"prompt": "Would you rather accidentally send an embarrassing text to", "category": "funny",
     "option_a": "Your boss", "emoji_a": "📱",
     "option_b": "Your ex", "emoji_b": "😬"},
]

# ----------------------------------------------------------------- Deep
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always know the full truth, even when it hurts", "emoji_a": "🔍",
     "option_b": "Sometimes be shielded from hard truths", "emoji_b": "🛡️"},
    {"prompt": "Would you rather have more", "category": "deep",
     "option_a": "Time", "emoji_a": "⏳",
     "option_b": "Money", "emoji_b": "💰"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Understood a little by everyone", "emoji_a": "🌍",
     "option_b": "Deeply understood by just one person", "emoji_b": "❤️"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Never fight again", "emoji_a": "🕊️",
     "option_b": "Always resolve every fight perfectly", "emoji_b": "🤝"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Relive your favourite memory forever", "emoji_a": "🔁",
     "option_b": "Keep making new ones, even if they fade", "emoji_b": "✨"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Fearless", "emoji_a": "🦁",
     "option_b": "Endlessly patient", "emoji_b": "🧘"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Know exactly how your story ends", "emoji_a": "📖",
     "option_b": "Be surprised by every twist", "emoji_b": "❓"},
    {"prompt": "Would you rather give up", "category": "deep",
     "option_a": "Your phone for a year", "emoji_a": "📵",
     "option_b": "Caffeine for a year", "emoji_b": "☕"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always speak your mind", "emoji_a": "🗯️",
     "option_b": "Always keep the peace", "emoji_b": "🤫"},
    {"prompt": "Would you rather have", "category": "deep",
     "option_a": "One big, unforgettable adventure", "emoji_a": "🏔️",
     "option_b": "Many small, quiet ones", "emoji_b": "🌤️"},
]

# ------------------------------------------------------------------ Spicy
# Adults-only, dual opt-in (see app/services/privacy.py: spicy_unlocked).
# Explicit by design - both partners have already confirmed they're 18+
# and both opted in before any of this is ever reachable. Gating is
# automatic: app/routes/activities.py hides any ActivityContent with
# category="spicy" everywhere while locked, and treats it as a fully
# normal category (including in unfiltered "All" history) once unlocked -
# no per-question gating logic needed here.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try anal for the first time together", "emoji_a": "🍑",
     "option_b": "Try a new toy together for the first time", "emoji_b": "🎛️"},
    {"prompt": "Would you rather we", "category": "spicy",
     "option_a": "Use a blindfold during sex", "emoji_a": "🙈",
     "option_b": "Use light restraints during sex", "emoji_b": "🔗"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Film a private video together, just for us", "emoji_a": "🎥",
     "option_b": "Take private photos together, just for us", "emoji_b": "📸"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "I take full control in bed", "emoji_a": "😈",
     "option_b": "You take full control in bed", "emoji_b": "🔥"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have sex somewhere in the house we've never tried", "emoji_a": "🏠",
     "option_b": "Have sex somewhere outside the house, discreetly", "emoji_b": "🌙"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Give oral", "emoji_a": "👅",
     "option_b": "Receive oral", "emoji_b": "💦"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Talk dirty during sex", "emoji_a": "💬",
     "option_b": "Stay quiet and let the moment speak for itself", "emoji_b": "🤫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Use a vibrator together", "emoji_a": "🔌",
     "option_b": "Use massage oil together", "emoji_b": "🧴"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new position tonight", "emoji_a": "🔀",
     "option_b": "Take it slow with something familiar tonight", "emoji_b": "🐢"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be tied up", "emoji_a": "🪢",
     "option_b": "Be the one tying up", "emoji_b": "🎀"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try light spanking", "emoji_a": "✋",
     "option_b": "Try leaving hickeys/marks", "emoji_b": "💋"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Act out a roleplay scenario together", "emoji_a": "🎭",
     "option_b": "Read/watch something together for inspiration first", "emoji_b": "📖"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have a quickie", "emoji_a": "⚡",
     "option_b": "Take your time, all night", "emoji_b": "🌌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try edging (build up, then hold off) together", "emoji_a": "⏳",
     "option_b": "Go straight for it, no teasing", "emoji_b": "🎯"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Shower together first", "emoji_a": "🚿",
     "option_b": "Skip straight to it", "emoji_b": "🔥"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "I initiate tonight", "emoji_a": "😏",
     "option_b": "You initiate tonight", "emoji_b": "😉"},
]

# ------------------------------------------------------- Spicy - Expanded
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "A 'no rules' night", "emoji_a": "🔓",
     "option_b": "A slow, romantic night", "emoji_b": "🕯️"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new toy", "emoji_a": "🎛️",
     "option_b": "Try a new position", "emoji_b": "🔀"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be surprised by your partner", "emoji_a": "🎁",
     "option_b": "Plan the whole night yourself", "emoji_b": "📋"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try roleplay with costumes", "emoji_a": "🎭",
     "option_b": "Try a fantasy scenario, no costumes needed", "emoji_b": "💭"},
    {"prompt": "Would you rather have sex", "category": "spicy",
     "option_a": "In the morning", "emoji_a": "🌅",
     "option_b": "At night", "emoji_b": "🌙"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be extra vocal", "emoji_a": "📢",
     "option_b": "Be extra quiet", "emoji_b": "🤫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Take a long bath or shower together first", "emoji_a": "🛁",
     "option_b": "Skip straight to it", "emoji_b": "⚡"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new spot in the house", "emoji_a": "🏠",
     "option_b": "Recreate your favourite memory together", "emoji_b": "💫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Give a massage that leads somewhere", "emoji_a": "💆",
     "option_b": "Receive a massage that leads somewhere", "emoji_b": "😌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try mutual masturbation", "emoji_a": "👀",
     "option_b": "Watch each other undress slowly", "emoji_b": "🔥"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A blindfold", "emoji_a": "🙈",
     "option_b": "Restraints", "emoji_b": "🔗"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a quickie before work", "emoji_a": "⏰",
     "option_b": "Plan an entire evening around it", "emoji_b": "🌌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Send flirty texts building up to it", "emoji_a": "💬",
     "option_b": "Save all the talk for the moment itself", "emoji_b": "🤐"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a themed date night leading to intimacy", "emoji_a": "🎉",
     "option_b": "Keep it completely spontaneous, no plan at all", "emoji_b": "🎲"},
]

# --------------------------------------------- Spicy - Advanced/Specific
# Same reasoning as seed_questions.py's "Advanced/Specific Expansion":
# for a couple past the "would you try X" stage - these ask which
# specific variant, implement, position, pace, or detail within an
# already-comfortable activity, not whether to try the activity at all.
# spicy_level 3 throughout.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather anal be", "category": "spicy",
     "option_a": "Slow, deep thrusts", "emoji_a": "🐌",
     "option_b": "Fast, shallow thrusts", "emoji_b": "⚡"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A vibrating butt plug", "emoji_a": "🎛️",
     "option_b": "A small vibrator against the entrance", "emoji_b": "🔘"},
    {"prompt": "Would you rather be restrained with", "category": "spicy",
     "option_a": "Rope", "emoji_a": "🪢",
     "option_b": "Cuffs", "emoji_b": "⛓️"},
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "Predicament bondage - real effort to stay still", "emoji_a": "😤",
     "option_b": "Simple restraint - can't move much either way", "emoji_b": "😌"},
    {"prompt": "Would you rather, during anal, I", "category": "spicy",
     "option_a": "Finish inside", "emoji_a": "💦",
     "option_b": "Pull out and finish somewhere else", "emoji_b": "🔀"},
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "A wand vibrator - broad and intense", "emoji_a": "🌊",
     "option_b": "A bullet vibrator - precise and small", "emoji_b": "🎯"},
    {"prompt": "Would you rather do anal", "category": "spicy",
     "option_a": "Doggy, so you control the depth", "emoji_a": "🐕",
     "option_b": "On your back, legs pushed up", "emoji_b": "🔼"},
    {"prompt": "Would you rather I", "category": "spicy",
     "option_a": "Rim you before using fingers", "emoji_a": "👅",
     "option_b": "Use fingers before rimming", "emoji_b": "✌️"},
    {"prompt": "Would you rather add", "category": "spicy",
     "option_a": "A blindfold to the restraints", "emoji_a": "🙈",
     "option_b": "A gag to the restraints", "emoji_b": "🤐"},
    {"prompt": "Would you rather film it", "category": "spicy",
     "option_a": "POV, handheld", "emoji_a": "📱",
     "option_b": "Wide shot, phone propped up", "emoji_b": "🎬"},
    {"prompt": "Would you rather be spanked with", "category": "spicy",
     "option_a": "An open hand", "emoji_a": "✋",
     "option_b": "A proper paddle", "emoji_b": "🏓"},
    {"prompt": "Would you rather have your hair pulled", "category": "spicy",
     "option_a": "As a light, firm tug", "emoji_a": "💫",
     "option_b": "Hard enough to control the angle of your head", "emoji_b": "🔥"},
    {"prompt": "Would you rather hear, during rough sex", "category": "spicy",
     "option_a": "Degrading dirty talk", "emoji_a": "😈",
     "option_b": "Praise, even while it's rough", "emoji_b": "🥰"},
    {"prompt": "Would you rather wear a butt plug", "category": "spicy",
     "option_a": "For a while before sex even starts", "emoji_a": "⏱️",
     "option_b": "Only during", "emoji_b": "🎯"},
    {"prompt": "Would you rather rough sex", "category": "spicy",
     "option_a": "Start rough from the first thrust", "emoji_a": "💥",
     "option_b": "Build slowly into rough", "emoji_b": "📈"},
    {"prompt": "Would you rather wear a remote-control toy", "category": "spicy",
     "option_a": "Out somewhere, under your clothes", "emoji_a": "🌃",
     "option_b": "Only ever at home", "emoji_b": "🏠"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "Anal beads", "emoji_a": "📿",
     "option_b": "A prostate massager", "emoji_b": "🎯"},
    {"prompt": "Would you rather be tied", "category": "spicy",
     "option_a": "To the headboard", "emoji_a": "🛏️",
     "option_b": "With hands pinned, nothing actually tied", "emoji_b": "🤲"},
    {"prompt": "Would you rather, once restrained, have", "category": "spicy",
     "option_a": "A long build-up before anything happens", "emoji_a": "⏳",
     "option_b": "Just a minute of teasing, then get to it", "emoji_b": "⚡"},
    {"prompt": "Would you rather anal be", "category": "spicy",
     "option_a": "Slow and intimate", "emoji_a": "💕",
     "option_b": "Rough and intense", "emoji_b": "🔥"},
    {"prompt": "Would you rather be hit with", "category": "spicy",
     "option_a": "A flogger", "emoji_a": "🎏",
     "option_b": "A belt", "emoji_b": "➰"},
    {"prompt": "Would you rather use a toy", "category": "spicy",
     "option_a": "Double-ended, on each other at once", "emoji_a": "🔁",
     "option_b": "One toy, taking turns", "emoji_b": "🔂"},
    {"prompt": "Would you rather a dildo be", "category": "spicy",
     "option_a": "Bigger than usual", "emoji_a": "📏",
     "option_b": "More textured or ribbed", "emoji_b": "〰️"},
    {"prompt": "Would you rather add, for sensory deprivation", "category": "spicy",
     "option_a": "Ear plugs or headphones", "emoji_a": "🔇",
     "option_b": "A blindfold", "emoji_b": "🙈"},
    {"prompt": "Would you rather use a spreader bar at", "category": "spicy",
     "option_a": "Your ankles", "emoji_a": "🦵",
     "option_b": "Your wrists", "emoji_b": "🙌"},
    {"prompt": "Would you rather prep for anal with", "category": "spicy",
     "option_a": "Just fingers", "emoji_a": "✌️",
     "option_b": "A small toy first", "emoji_b": "🎛️"},
    {"prompt": "Would you rather anal go", "category": "spicy",
     "option_a": "As deep as comfortably possible", "emoji_a": "🔽",
     "option_b": "Shallow and controlled the whole time", "emoji_b": "🎚️"},
    {"prompt": "Would you rather film", "category": "spicy",
     "option_a": "The whole scene, start to finish", "emoji_a": "🎬",
     "option_b": "Just one specific act", "emoji_b": "✂️"},
    {"prompt": "Would you rather we take", "category": "spicy",
     "option_a": "Photos, no video", "emoji_a": "📸",
     "option_b": "Audio only, no video", "emoji_b": "🎙️"},
    {"prompt": "Would you rather, during oral, I use", "category": "spicy",
     "option_a": "A toy on you at the same time", "emoji_a": "🎛️",
     "option_b": "Just my mouth and hands", "emoji_b": "👄"},
    {"prompt": "Would you rather rough sex be", "category": "spicy",
     "option_a": "Full of talking", "emoji_a": "💬",
     "option_b": "Mostly just sounds", "emoji_b": "🔊"},
    {"prompt": "Would you rather add, during anal", "category": "spicy",
     "option_a": "A vibrator on me at the same time", "emoji_a": "🎛️",
     "option_b": "Nothing else, just anal", "emoji_b": "🎯"},
    {"prompt": "Would you rather rope be", "category": "spicy",
     "option_a": "Decorative, meant to look good", "emoji_a": "🎀",
     "option_b": "Purely functional, just to keep still", "emoji_b": "🔒"},
    {"prompt": "Would you rather anal", "category": "spicy",
     "option_a": "Start small and build up in size", "emoji_a": "📈",
     "option_b": "Go straight to your usual size", "emoji_b": "➡️"},
    {"prompt": "Would you rather film with", "category": "spicy",
     "option_a": "A mirror we can watch ourselves in", "emoji_a": "🪞",
     "option_b": "A proper camera on a tripod", "emoji_b": "📷"},
    {"prompt": "Would you rather be spanked", "category": "spicy",
     "option_a": "Hard enough to mark", "emoji_a": "🔥",
     "option_b": "Light, more sting than force", "emoji_b": "🪶"},
    {"prompt": "Would you rather wear", "category": "spicy",
     "option_a": "A gag, so you can't talk", "emoji_a": "🤐",
     "option_b": "A blindfold, so you can't see", "emoji_b": "🙈"},
    {"prompt": "Would you rather be restrained with", "category": "spicy",
     "option_a": "One hand tied, one free", "emoji_a": "🤚",
     "option_b": "Both hands tied", "emoji_b": "🙌"},
    {"prompt": "Would you rather control the pace during anal by", "category": "spicy",
     "option_a": "Being on top yourself", "emoji_a": "🎢",
     "option_b": "Directing me while I set it", "emoji_b": "🕹️"},
    {"prompt": "Would you rather rimming be", "category": "spicy",
     "option_a": "Just enough to get you ready", "emoji_a": "⏱️",
     "option_b": "An extended thing on its own", "emoji_b": "🕰️"},
    {"prompt": "Would you rather, finishing anal, I", "category": "spicy",
     "option_a": "Pull out and finish on you", "emoji_a": "🔀",
     "option_b": "Switch to vaginal to finish", "emoji_b": "↩️"},
    {"prompt": "Would you rather wear a butt plug", "category": "spicy",
     "option_a": "Out in public, under your clothes", "emoji_a": "👖",
     "option_b": "Only ever at home", "emoji_b": "🏠"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A vibrating cock ring", "emoji_a": "⚡",
     "option_b": "A regular one", "emoji_b": "💍"},
    {"prompt": "Would you rather be tied", "category": "spicy",
     "option_a": "For something light and quick", "emoji_a": "🎀",
     "option_b": "For a full, drawn-out scene", "emoji_b": "🕯️"},
]
