"""
The Would You Rather content bank. Seeded directly into ActivityContent
(activity_type="would_you_rather") - there's no legacy-system equivalent
to migrate from, this game only ever exists in the new Activity system.

Each entry: prompt (shown above both options), category (normal/funny/deep),
option_a/option_b (the two choices), and optional emoji_a/emoji_b for a
little visual flair on each option card.
"""

WOULD_YOU_RATHER_QUESTIONS = []

# --------------------------------------------------------------- Normal
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Spend a week on a tropical island", "emoji_a": "🏝️",
     "option_b": "Spend a week in the mountains", "emoji_b": "🏔️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A home-cooked candlelit dinner", "emoji_a": "🍝",
     "option_b": "A fancy night out at a restaurant", "emoji_b": "🥂"},
    {"prompt": "Would you rather go on", "category": "normal",
     "option_a": "A big trip with friends", "emoji_a": "👯",
     "option_b": "A quiet getaway just the two of us", "emoji_b": "💕"},
    {"prompt": "Would you rather we", "category": "normal",
     "option_a": "Wake up early together", "emoji_a": "🌅",
     "option_b": "Sleep in together", "emoji_b": "😴"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A spontaneous surprise trip", "emoji_a": "🎒",
     "option_b": "A carefully planned dream vacation", "emoji_b": "🗺️"},
    {"prompt": "Would you rather live in", "category": "normal",
     "option_a": "The city", "emoji_a": "🏙️",
     "option_b": "The countryside", "emoji_b": "🌾"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A movie night at home", "emoji_a": "🛋️",
     "option_b": "A night out at the cinema", "emoji_b": "🎬"},
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Cook a meal together", "emoji_a": "👩‍🍳",
     "option_b": "Order in and relax", "emoji_b": "🥡"},
    {"prompt": "Would you rather take", "category": "normal",
     "option_a": "A road trip", "emoji_a": "🚗",
     "option_b": "A flight somewhere far away", "emoji_b": "✈️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A big birthday party", "emoji_a": "🎉",
     "option_b": "A quiet birthday just for two", "emoji_b": "🕯️"},
    {"prompt": "Would you rather stay in", "category": "normal",
     "option_a": "A beach house", "emoji_a": "🏖️",
     "option_b": "A cabin in the woods", "emoji_b": "🛖"},
    {"prompt": "Would you rather save up for", "category": "normal",
     "option_a": "A house", "emoji_a": "🏡",
     "option_b": "A year of travel", "emoji_b": "🧳"},
]

# ---------------------------------------------------------------- Funny
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Only communicate in memes for a week", "emoji_a": "😂",
     "option_b": "Only communicate in song lyrics for a week", "emoji_b": "🎤"},
    {"prompt": "Would you rather fight", "category": "funny",
     "option_a": "One horse-sized duck", "emoji_a": "🦆",
     "option_b": "A hundred duck-sized horses", "emoji_b": "🐴"},
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Have to sing instead of talk, forever", "emoji_a": "🎶",
     "option_b": "Have to dance instead of walk, forever", "emoji_b": "💃"},
    {"prompt": "Would you rather never eat", "category": "funny",
     "option_a": "Pizza again", "emoji_a": "🍕",
     "option_b": "Another movie night snack again", "emoji_b": "🍿"},
    {"prompt": "Would you rather be able to talk to", "category": "funny",
     "option_a": "Animals", "emoji_a": "🐶",
     "option_b": "Plants", "emoji_b": "🌱"},
    {"prompt": "Would you rather have to", "category": "funny",
     "option_a": "Wear a costume every day for a month", "emoji_a": "🦸",
     "option_b": "Speak in an accent every day for a month", "emoji_b": "🗣️"},
    {"prompt": "Would you rather time travel to", "category": "funny",
     "option_a": "The past", "emoji_a": "⏪",
     "option_b": "The future", "emoji_b": "⏩"},
    {"prompt": "Would you rather I become a famous", "category": "funny",
     "option_a": "Chef", "emoji_a": "👨‍🍳",
     "option_b": "Musician", "emoji_b": "🎸"},
    {"prompt": "Would you rather have", "category": "funny",
     "option_a": "Unlimited snacks but no naps", "emoji_a": "🍪",
     "option_b": "Unlimited naps but no snacks", "emoji_b": "😴"},
    {"prompt": "Would you rather accidentally send an embarrassing text to", "category": "funny",
     "option_a": "Your boss", "emoji_a": "📱",
     "option_b": "Your ex", "emoji_b": "😬"},
]

# ----------------------------------------------------------------- Deep
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always know the full truth, even when it hurts", "emoji_a": "🔍",
     "option_b": "Sometimes be shielded from hard truths", "emoji_b": "🛡️"},
    {"prompt": "Would you rather have more", "category": "deep",
     "option_a": "Time", "emoji_a": "⏳",
     "option_b": "Money", "emoji_b": "💰"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Understood a little by everyone", "emoji_a": "🌍",
     "option_b": "Deeply understood by just one person", "emoji_b": "❤️"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Never fight again", "emoji_a": "🕊️",
     "option_b": "Always resolve every fight perfectly", "emoji_b": "🤝"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Relive your favourite memory forever", "emoji_a": "🔁",
     "option_b": "Keep making new ones, even if they fade", "emoji_b": "✨"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Fearless", "emoji_a": "🦁",
     "option_b": "Endlessly patient", "emoji_b": "🧘"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Know exactly how your story ends", "emoji_a": "📖",
     "option_b": "Be surprised by every twist", "emoji_b": "❓"},
    {"prompt": "Would you rather give up", "category": "deep",
     "option_a": "Your phone for a year", "emoji_a": "📵",
     "option_b": "Caffeine for a year", "emoji_b": "☕"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always speak your mind", "emoji_a": "🗯️",
     "option_b": "Always keep the peace", "emoji_b": "🤫"},
    {"prompt": "Would you rather have", "category": "deep",
     "option_a": "One big, unforgettable adventure", "emoji_a": "🏔️",
     "option_b": "Many small, quiet ones", "emoji_b": "🌤️"},
]

# ------------------------------------------------------------------ Spicy
# Adults-only, dual opt-in (see app/services/privacy.py: spicy_unlocked).
# Explicit by design - both partners have already confirmed they're 18+
# and both opted in before any of this is ever reachable. Gating is
# automatic: app/routes/activities.py hides any ActivityContent with
# category="spicy" everywhere while locked, and treats it as a fully
# normal category (including in unfiltered "All" history) once unlocked -
# no per-question gating logic needed here.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try anal for the first time together", "emoji_a": "🍑",
     "option_b": "Try a new toy together for the first time", "emoji_b": "🎛️"},
    {"prompt": "Would you rather we", "category": "spicy",
     "option_a": "Use a blindfold during sex", "emoji_a": "🙈",
     "option_b": "Use light restraints during sex", "emoji_b": "🔗"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Film a private video together, just for us", "emoji_a": "🎥",
     "option_b": "Take private photos together, just for us", "emoji_b": "📸"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "I take full control in bed", "emoji_a": "😈",
     "option_b": "You take full control in bed", "emoji_b": "🔥"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have sex somewhere in the house we've never tried", "emoji_a": "🏠",
     "option_b": "Have sex somewhere outside the house, discreetly", "emoji_b": "🌙"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Give oral", "emoji_a": "👅",
     "option_b": "Receive oral", "emoji_b": "💦"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Talk dirty during sex", "emoji_a": "💬",
     "option_b": "Stay quiet and let the moment speak for itself", "emoji_b": "🤫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Use a vibrator together", "emoji_a": "🔌",
     "option_b": "Use massage oil together", "emoji_b": "🧴"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new position tonight", "emoji_a": "🔀",
     "option_b": "Take it slow with something familiar tonight", "emoji_b": "🐢"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be tied up", "emoji_a": "🪢",
     "option_b": "Be the one tying up", "emoji_b": "🎀"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try light spanking", "emoji_a": "✋",
     "option_b": "Try leaving hickeys/marks", "emoji_b": "💋"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Act out a roleplay scenario together", "emoji_a": "🎭",
     "option_b": "Read/watch something together for inspiration first", "emoji_b": "📖"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have a quickie", "emoji_a": "⚡",
     "option_b": "Take your time, all night", "emoji_b": "🌌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try edging (build up, then hold off) together", "emoji_a": "⏳",
     "option_b": "Go straight for it, no teasing", "emoji_b": "🎯"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Shower together first", "emoji_a": "🚿",
     "option_b": "Skip straight to it", "emoji_b": "🔥"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "I initiate tonight", "emoji_a": "😏",
     "option_b": "You initiate tonight", "emoji_b": "😉"},
]

# ------------------------------------------------------- Spicy - Expanded
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "A 'no rules' night", "emoji_a": "🔓",
     "option_b": "A slow, romantic night", "emoji_b": "🕯️"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new toy", "emoji_a": "🎛️",
     "option_b": "Try a new position", "emoji_b": "🔀"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be surprised by your partner", "emoji_a": "🎁",
     "option_b": "Plan the whole night yourself", "emoji_b": "📋"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try roleplay with costumes", "emoji_a": "🎭",
     "option_b": "Try a fantasy scenario, no costumes needed", "emoji_b": "💭"},
    {"prompt": "Would you rather have sex", "category": "spicy",
     "option_a": "In the morning", "emoji_a": "🌅",
     "option_b": "At night", "emoji_b": "🌙"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be extra vocal", "emoji_a": "📢",
     "option_b": "Be extra quiet", "emoji_b": "🤫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Take a long bath or shower together first", "emoji_a": "🛁",
     "option_b": "Skip straight to it", "emoji_b": "⚡"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a new spot in the house", "emoji_a": "🏠",
     "option_b": "Recreate your favourite memory together", "emoji_b": "💫"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Give a massage that leads somewhere", "emoji_a": "💆",
     "option_b": "Receive a massage that leads somewhere", "emoji_b": "😌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try mutual masturbation", "emoji_a": "👀",
     "option_b": "Watch each other undress slowly", "emoji_b": "🔥"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A blindfold", "emoji_a": "🙈",
     "option_b": "Restraints", "emoji_b": "🔗"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a quickie before work", "emoji_a": "⏰",
     "option_b": "Plan an entire evening around it", "emoji_b": "🌌"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Send flirty texts building up to it", "emoji_a": "💬",
     "option_b": "Save all the talk for the moment itself", "emoji_b": "🤐"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Try a themed date night leading to intimacy", "emoji_a": "🎉",
     "option_b": "Keep it completely spontaneous, no plan at all", "emoji_b": "🎲"},
]

# --------------------------------------------- Spicy - Advanced/Specific
# Same reasoning as seed_questions.py's "Advanced/Specific Expansion":
# for a couple past the "would you try X" stage - these ask which
# specific variant, implement, position, pace, or detail within an
# already-comfortable activity, not whether to try the activity at all.
# spicy_level 3 throughout.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather anal be", "category": "spicy",
     "option_a": "Slow, deep thrusts", "emoji_a": "🐌",
     "option_b": "Fast, shallow thrusts", "emoji_b": "⚡"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A vibrating butt plug", "emoji_a": "🎛️",
     "option_b": "A small vibrator against the entrance", "emoji_b": "🔘"},
    {"prompt": "Would you rather be restrained with", "category": "spicy",
     "option_a": "Rope", "emoji_a": "🪢",
     "option_b": "Cuffs", "emoji_b": "⛓️"},
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "Predicament bondage - real effort to stay still", "emoji_a": "😤",
     "option_b": "Simple restraint - can't move much either way", "emoji_b": "😌"},
    {"prompt": "Would you rather, during anal, I", "category": "spicy",
     "option_a": "Finish inside", "emoji_a": "💦",
     "option_b": "Pull out and finish somewhere else", "emoji_b": "🔀"},
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "A wand vibrator - broad and intense", "emoji_a": "🌊",
     "option_b": "A bullet vibrator - precise and small", "emoji_b": "🎯"},
    {"prompt": "Would you rather do anal", "category": "spicy",
     "option_a": "Doggy, so you control the depth", "emoji_a": "🐕",
     "option_b": "On your back, legs pushed up", "emoji_b": "🔼"},
    {"prompt": "Would you rather I", "category": "spicy",
     "option_a": "Rim you before using fingers", "emoji_a": "👅",
     "option_b": "Use fingers before rimming", "emoji_b": "✌️"},
    {"prompt": "Would you rather add", "category": "spicy",
     "option_a": "A blindfold to the restraints", "emoji_a": "🙈",
     "option_b": "A gag to the restraints", "emoji_b": "🤐"},
    {"prompt": "Would you rather film it", "category": "spicy",
     "option_a": "POV, handheld", "emoji_a": "📱",
     "option_b": "Wide shot, phone propped up", "emoji_b": "🎬"},
    {"prompt": "Would you rather be spanked with", "category": "spicy",
     "option_a": "An open hand", "emoji_a": "✋",
     "option_b": "A proper paddle", "emoji_b": "🏓"},
    {"prompt": "Would you rather have your hair pulled", "category": "spicy",
     "option_a": "As a light, firm tug", "emoji_a": "💫",
     "option_b": "Hard enough to control the angle of your head", "emoji_b": "🔥"},
    {"prompt": "Would you rather hear, during rough sex", "category": "spicy",
     "option_a": "Degrading dirty talk", "emoji_a": "😈",
     "option_b": "Praise, even while it's rough", "emoji_b": "🥰"},
    {"prompt": "Would you rather wear a butt plug", "category": "spicy",
     "option_a": "For a while before sex even starts", "emoji_a": "⏱️",
     "option_b": "Only during", "emoji_b": "🎯"},
    {"prompt": "Would you rather rough sex", "category": "spicy",
     "option_a": "Start rough from the first thrust", "emoji_a": "💥",
     "option_b": "Build slowly into rough", "emoji_b": "📈"},
    {"prompt": "Would you rather wear a remote-control toy", "category": "spicy",
     "option_a": "Out somewhere, under your clothes", "emoji_a": "🌃",
     "option_b": "Only ever at home", "emoji_b": "🏠"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "Anal beads", "emoji_a": "📿",
     "option_b": "A prostate massager", "emoji_b": "🎯"},
    {"prompt": "Would you rather be tied", "category": "spicy",
     "option_a": "To the headboard", "emoji_a": "🛏️",
     "option_b": "With hands pinned, nothing actually tied", "emoji_b": "🤲"},
    {"prompt": "Would you rather, once restrained, have", "category": "spicy",
     "option_a": "A long build-up before anything happens", "emoji_a": "⏳",
     "option_b": "Just a minute of teasing, then get to it", "emoji_b": "⚡"},
    {"prompt": "Would you rather anal be", "category": "spicy",
     "option_a": "Slow and intimate", "emoji_a": "💕",
     "option_b": "Rough and intense", "emoji_b": "🔥"},
    {"prompt": "Would you rather be hit with", "category": "spicy",
     "option_a": "A flogger", "emoji_a": "🎏",
     "option_b": "A belt", "emoji_b": "➰"},
    {"prompt": "Would you rather use a toy", "category": "spicy",
     "option_a": "Double-ended, on each other at once", "emoji_a": "🔁",
     "option_b": "One toy, taking turns", "emoji_b": "🔂"},
    {"prompt": "Would you rather a dildo be", "category": "spicy",
     "option_a": "Bigger than usual", "emoji_a": "📏",
     "option_b": "More textured or ribbed", "emoji_b": "〰️"},
    {"prompt": "Would you rather add, for sensory deprivation", "category": "spicy",
     "option_a": "Ear plugs or headphones", "emoji_a": "🔇",
     "option_b": "A blindfold", "emoji_b": "🙈"},
    {"prompt": "Would you rather use a spreader bar at", "category": "spicy",
     "option_a": "Your ankles", "emoji_a": "🦵",
     "option_b": "Your wrists", "emoji_b": "🙌"},
    {"prompt": "Would you rather prep for anal with", "category": "spicy",
     "option_a": "Just fingers", "emoji_a": "✌️",
     "option_b": "A small toy first", "emoji_b": "🎛️"},
    {"prompt": "Would you rather anal go", "category": "spicy",
     "option_a": "As deep as comfortably possible", "emoji_a": "🔽",
     "option_b": "Shallow and controlled the whole time", "emoji_b": "🎚️"},
    {"prompt": "Would you rather film", "category": "spicy",
     "option_a": "The whole scene, start to finish", "emoji_a": "🎬",
     "option_b": "Just one specific act", "emoji_b": "✂️"},
    {"prompt": "Would you rather we take", "category": "spicy",
     "option_a": "Photos, no video", "emoji_a": "📸",
     "option_b": "Audio only, no video", "emoji_b": "🎙️"},
    {"prompt": "Would you rather, during oral, I use", "category": "spicy",
     "option_a": "A toy on you at the same time", "emoji_a": "🎛️",
     "option_b": "Just my mouth and hands", "emoji_b": "👄"},
    {"prompt": "Would you rather rough sex be", "category": "spicy",
     "option_a": "Full of talking", "emoji_a": "💬",
     "option_b": "Mostly just sounds", "emoji_b": "🔊"},
    {"prompt": "Would you rather add, during anal", "category": "spicy",
     "option_a": "A vibrator on me at the same time", "emoji_a": "🎛️",
     "option_b": "Nothing else, just anal", "emoji_b": "🎯"},
    {"prompt": "Would you rather rope be", "category": "spicy",
     "option_a": "Decorative, meant to look good", "emoji_a": "🎀",
     "option_b": "Purely functional, just to keep still", "emoji_b": "🔒"},
    {"prompt": "Would you rather anal", "category": "spicy",
     "option_a": "Start small and build up in size", "emoji_a": "📈",
     "option_b": "Go straight to your usual size", "emoji_b": "➡️"},
    {"prompt": "Would you rather film with", "category": "spicy",
     "option_a": "A mirror we can watch ourselves in", "emoji_a": "🪞",
     "option_b": "A proper camera on a tripod", "emoji_b": "📷"},
    {"prompt": "Would you rather be spanked", "category": "spicy",
     "option_a": "Hard enough to mark", "emoji_a": "🔥",
     "option_b": "Light, more sting than force", "emoji_b": "🪶"},
    {"prompt": "Would you rather wear", "category": "spicy",
     "option_a": "A gag, so you can't talk", "emoji_a": "🤐",
     "option_b": "A blindfold, so you can't see", "emoji_b": "🙈"},
    {"prompt": "Would you rather be restrained with", "category": "spicy",
     "option_a": "One hand tied, one free", "emoji_a": "🤚",
     "option_b": "Both hands tied", "emoji_b": "🙌"},
    {"prompt": "Would you rather control the pace during anal by", "category": "spicy",
     "option_a": "Being on top yourself", "emoji_a": "🎢",
     "option_b": "Directing me while I set it", "emoji_b": "🕹️"},
    {"prompt": "Would you rather rimming be", "category": "spicy",
     "option_a": "Just enough to get you ready", "emoji_a": "⏱️",
     "option_b": "An extended thing on its own", "emoji_b": "🕰️"},
    {"prompt": "Would you rather, finishing anal, I", "category": "spicy",
     "option_a": "Pull out and finish on you", "emoji_a": "🔀",
     "option_b": "Switch to vaginal to finish", "emoji_b": "↩️"},
    {"prompt": "Would you rather wear a butt plug", "category": "spicy",
     "option_a": "Out in public, under your clothes", "emoji_a": "👖",
     "option_b": "Only ever at home", "emoji_b": "🏠"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "A vibrating cock ring", "emoji_a": "⚡",
     "option_b": "A regular one", "emoji_b": "💍"},
    {"prompt": "Would you rather be tied", "category": "spicy",
     "option_a": "For something light and quick", "emoji_a": "🎀",
     "option_b": "For a full, drawn-out scene", "emoji_b": "🕯️"},
]

# ------------------------------------------------ Spicy - New Themes
# Fantasy, sensory, roleplay, communication and aftercare-focused.
# Deliberately capped at the same level as the Spicy / Spicy - Expanded
# sections above (naming acts, dynamics and preferences) rather than the
# Advanced/Specific tier's mechanical detail - new ground, not more depth.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather set the mood with", "category": "spicy",
     "option_a": "Candlelight and low lighting", "emoji_a": "🕯️",
     "option_b": "Total darkness", "emoji_b": "🌑"},
    {"prompt": "Would you rather use, for temperature play", "category": "spicy",
     "option_a": "Warm massage oil", "emoji_a": "🔥",
     "option_b": "Ice", "emoji_b": "🧊"},
    {"prompt": "Would you rather set the scene with", "category": "spicy",
     "option_a": "A specific playlist", "emoji_a": "🎶",
     "option_b": "Silence, just each other", "emoji_b": "🤍"},
    {"prompt": "Would you rather leave", "category": "spicy",
     "option_a": "The curtains open a crack", "emoji_a": "🌆",
     "option_b": "Everything fully closed off", "emoji_b": "🔒"},
    {"prompt": "Would you rather roleplay", "category": "spicy",
     "option_a": "Meeting as strangers for the first time", "emoji_a": "🍸",
     "option_b": "A forbidden, secret rendezvous", "emoji_b": "🤫"},
    {"prompt": "Would you rather roleplay", "category": "spicy",
     "option_a": "A rockstar and an obsessed fan", "emoji_a": "🎸",
     "option_b": "A boss and someone trying to impress them", "emoji_b": "💼"},
    {"prompt": "Would you rather roleplay", "category": "spicy",
     "option_a": "Reuniting after years apart", "emoji_a": "✈️",
     "option_b": "A massage that gets a little too personal", "emoji_b": "💆"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Give up control completely for the night", "emoji_a": "🙇",
     "option_b": "Take charge without warning", "emoji_b": "😏"},
    {"prompt": "Would you rather share", "category": "spicy",
     "option_a": "A fantasy involving someone else, just to talk about", "emoji_a": "💭",
     "option_b": "Keep every fantasy just between the two of us", "emoji_b": "🔒"},
    {"prompt": "Would you rather write down a fantasy and", "category": "spicy",
     "option_a": "Swap and read them silently", "emoji_a": "📝",
     "option_b": "Read them out loud to each other", "emoji_b": "🗣️"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Keep eye contact the whole time", "emoji_a": "👀",
     "option_b": "Close your eyes and just feel it", "emoji_b": "😌"},
    {"prompt": "Would you rather start with", "category": "spicy",
     "option_a": "A slow kiss that builds", "emoji_a": "💋",
     "option_b": "A whispered compliment first", "emoji_b": "🗯️"},
    {"prompt": "Would you rather check in", "category": "spicy",
     "option_a": "Before trying something new, every time", "emoji_a": "✅",
     "option_b": "Trust the moment and adjust as you go", "emoji_b": "🌊"},
    {"prompt": "Would you rather wear", "category": "spicy",
     "option_a": "Lingerie, something you feel confident in", "emoji_a": "🖤",
     "option_b": "Nothing at all, no buildup needed", "emoji_b": "✨"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Undress each other slowly", "emoji_a": "🐌",
     "option_b": "Undress separately while watching", "emoji_b": "👗"},
    {"prompt": "Would you rather keep", "category": "spicy",
     "option_a": "Some clothes on the whole time", "emoji_a": "👕",
     "option_b": "Everything off from the start", "emoji_b": "🔥"},
    {"prompt": "Would you rather be touched with", "category": "spicy",
     "option_a": "A feather-light touch", "emoji_a": "🪶",
     "option_b": "Firm, deep pressure", "emoji_b": "💪"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Moan freely, no holding back", "emoji_a": "🔊",
     "option_b": "Try to stay quiet even when it's hard", "emoji_b": "🤫"},
    {"prompt": "Would you rather use", "category": "spicy",
     "option_a": "Pet names the whole time", "emoji_a": "🥰",
     "option_b": "No talking, just sounds and touch", "emoji_b": "🤐"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Cuddle immediately after", "emoji_a": "🫂",
     "option_b": "Take a minute apart to catch your breath first", "emoji_b": "😮‍💨"},
    {"prompt": "Would you rather, right after", "category": "spicy",
     "option_a": "Talk about how it felt", "emoji_a": "💬",
     "option_b": "Let it settle in comfortable silence", "emoji_b": "🤍"},
    {"prompt": "Would you rather, right after", "category": "spicy",
     "option_a": "Get playful and laugh together", "emoji_a": "😂",
     "option_b": "Stay serious and close", "emoji_b": "🥹"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Keep the same routine you both know works", "emoji_a": "🔁",
     "option_b": "Switch something up every single time", "emoji_b": "🔀"},
    {"prompt": "Would you rather plan", "category": "spicy",
     "option_a": "A 'spicy night' in advance, with anticipation building all day", "emoji_a": "📅",
     "option_b": "Let it happen completely spontaneously", "emoji_b": "🎲"},
    {"prompt": "Would you rather celebrate good news", "category": "spicy",
     "option_a": "With something spicy together", "emoji_a": "🎉",
     "option_b": "Save it for later and savor it slow", "emoji_b": "🕯️"},
    {"prompt": "Would you rather comfort each other after a hard day", "category": "spicy",
     "option_a": "With something slow and intimate", "emoji_a": "🫂",
     "option_b": "With something playful to lighten the mood", "emoji_b": "😄"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have a lazy, half-asleep morning session", "emoji_a": "😴",
     "option_b": "Have a wide-awake, energetic session", "emoji_b": "⚡"},
    {"prompt": "Would you rather have to stay quiet because", "category": "spicy",
     "option_a": "Someone else is in the next room", "emoji_a": "🤫",
     "option_b": "Wait until you're completely alone in the house", "emoji_b": "🏡"},
    {"prompt": "Would you rather a toy be controlled", "category": "spicy",
     "option_a": "By an app on your phone", "emoji_a": "📱",
     "option_b": "By hand, the old-fashioned way", "emoji_b": "✋"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Be teased for a long time before anything happens", "emoji_a": "⏳",
     "option_b": "Get straight to it, no teasing", "emoji_b": "🎯"},
    {"prompt": "Would you rather compliment", "category": "spicy",
     "option_a": "How your partner looks", "emoji_a": "😍",
     "option_b": "How your partner makes you feel", "emoji_b": "🥰"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Have a scent, candle or perfume, set the mood", "emoji_a": "🕯️",
     "option_b": "Keep everything unscented and natural", "emoji_b": "🌿"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Send a photo hinting at the night ahead", "emoji_a": "📸",
     "option_b": "Say nothing and let it be a surprise", "emoji_b": "🤐"},
    {"prompt": "Would you rather roleplay a scenario where", "category": "spicy",
     "option_a": "You're not supposed to be caught", "emoji_a": "🙊",
     "option_b": "No one else is even around to worry about", "emoji_b": "🏝️"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Take a long, warm shower together after", "emoji_a": "🚿",
     "option_b": "Just fall asleep tangled together after", "emoji_b": "😴"},
]

# --------------------------------------------- Spicy - Further Expansion
# Checked against every section above for overlap before writing these -
# each pair below covers an axis not already asked (slap location, grip
# during rough sex, mark visibility, orgasm order, session structure,
# restrained+oral combos, toy timing around restraint, footage watch
# timing, spanking rhythm, blindfold timing, dildo shape, a new roleplay
# pair, toy vantage point, anal's role in the scene, edging method,
# restrained posture, toy discretion, anal spontaneity, and how rough sex
# winds down). Nothing here repeats an existing dichotomy in different
# words.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather be slapped", "category": "spicy",
     "option_a": "Across the ass", "emoji_a": "🍑",
     "option_b": "Across the face, open palm", "emoji_b": "✋"},
    {"prompt": "Would you rather be gripped, during rough sex, by", "category": "spicy",
     "option_a": "A hand on the back of your neck, holding - not choking", "emoji_a": "✊",
     "option_b": "Wrists pinned hard against the bed", "emoji_b": "🙌"},
    {"prompt": "Would you rather marks left after", "category": "spicy",
     "option_a": "Be visible - you like seeing them", "emoji_a": "👀",
     "option_b": "Stay somewhere clothes will cover", "emoji_b": "👕"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Finish before your partner", "emoji_a": "🥇",
     "option_b": "Make your partner finish first", "emoji_b": "🎁"},
    {"prompt": "Would you rather have", "category": "spicy",
     "option_a": "One long, drawn-out round", "emoji_a": "🕰️",
     "option_b": "Multiple rounds in one night", "emoji_b": "🔁"},
    {"prompt": "Would you rather, while restrained,", "category": "spicy",
     "option_a": "Be the one receiving oral", "emoji_a": "😌",
     "option_b": "Be the one going down on your partner", "emoji_b": "👅"},
    {"prompt": "Would you rather a toy be used on you", "category": "spicy",
     "option_a": "While you're still restrained", "emoji_a": "🔗",
     "option_b": "Right after being untied", "emoji_b": "🔓"},
    {"prompt": "Would you rather watch back something you filmed", "category": "spicy",
     "option_a": "Together, right after", "emoji_a": "📺",
     "option_b": "Save it for another night", "emoji_b": "🗓️"},
    {"prompt": "Would you rather be spanked", "category": "spicy",
     "option_a": "In a steady, predictable rhythm", "emoji_a": "🥁",
     "option_b": "Randomly, so you can't anticipate it", "emoji_b": "🎲"},
    {"prompt": "Would you rather be blindfolded", "category": "spicy",
     "option_a": "During oral", "emoji_a": "👅",
     "option_b": "During penetration", "emoji_b": "🍑"},
    {"prompt": "Would you rather a dildo be", "category": "spicy",
     "option_a": "Longer", "emoji_a": "📏",
     "option_b": "Thicker", "emoji_b": "⭕"},
    {"prompt": "Would you rather roleplay", "category": "spicy",
     "option_a": "Running into an ex unexpectedly", "emoji_a": "👋",
     "option_b": "A blind date that goes further than planned", "emoji_b": "🍷"},
    {"prompt": "Would you rather I use a toy on you", "category": "spicy",
     "option_a": "Face to face, watching the whole time", "emoji_a": "👁️",
     "option_b": "From behind, out of sight", "emoji_b": "🔙"},
    {"prompt": "Would you rather anal be", "category": "spicy",
     "option_a": "The main event on its own", "emoji_a": "🎯",
     "option_b": "One part of switching between anal and vaginal", "emoji_b": "🔀"},
    {"prompt": "Would you rather be edged", "category": "spicy",
     "option_a": "By hand", "emoji_a": "✋",
     "option_b": "By a toy", "emoji_b": "🎛️"},
    {"prompt": "Would you rather be restrained", "category": "spicy",
     "option_a": "Sitting or kneeling", "emoji_a": "🧎",
     "option_b": "Lying down", "emoji_b": "🛏️"},
    {"prompt": "Would you rather use a toy that's", "category": "spicy",
     "option_a": "Loud enough you might get caught", "emoji_a": "🔊",
     "option_b": "Whisper-quiet, no one would ever know", "emoji_b": "🤫"},
    {"prompt": "Would you rather anal happen", "category": "spicy",
     "option_a": "Spontaneously, no warning", "emoji_a": "⚡",
     "option_b": "With a clear heads-up beforehand", "emoji_b": "📢"},
    {"prompt": "Would you rather try", "category": "spicy",
     "option_a": "Nipple clamps", "emoji_a": "📎",
     "option_b": "A vibrating cock ring", "emoji_b": "⚡"},
    {"prompt": "Would you rather rough sex", "category": "spicy",
     "option_a": "End with a sudden, intense finish", "emoji_a": "💥",
     "option_b": "Slow right down before finishing", "emoji_b": "📉"},
]

# ------------------------------------------------- Spicy - Round Three
# Same rule as last time: checked against every entry above (both
# original and the prior expansion) before writing these. Pushes into
# ground not touched yet - restraint extent/material/struggle, specific
# anal mechanics, toy dynamics, filming logistics, and rough-sex grip/
# kissing/naming detail. This is close to the point of genuine
# saturation for this format - a few more angles exist, but most
# remaining ones would just be a existing pair reworded, which isn't
# worth adding.
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather be restrained", "category": "spicy",
     "option_a": "Wrists only", "emoji_a": "⛓️",
     "option_b": "Wrists and ankles both", "emoji_b": "🔗"},
    {"prompt": "Would you rather be tied with", "category": "spicy",
     "option_a": "Something soft, like a scarf", "emoji_a": "🧣",
     "option_b": "Something rigid, like metal cuffs", "emoji_b": "⛓️"},
    {"prompt": "Would you rather, while restrained,", "category": "spicy",
     "option_a": "Be allowed to struggle against it", "emoji_a": "💪",
     "option_b": "Be expected to stay perfectly still", "emoji_b": "🧊"},
    {"prompt": "Would you rather be restrained with", "category": "spicy",
     "option_a": "Your legs held open", "emoji_a": "🦵",
     "option_b": "Your legs free to move", "emoji_b": "🚶"},
    {"prompt": "Would you rather, during anal, have", "category": "spicy",
     "option_a": "Your hands free to touch yourself too", "emoji_a": "🤲",
     "option_b": "Your hands occupied, no multitasking", "emoji_b": "✋"},
    {"prompt": "Would you rather finish anal with", "category": "spicy",
     "option_a": "The toy still inside you", "emoji_a": "🎛️",
     "option_b": "The toy removed first", "emoji_b": "🔚"},
    {"prompt": "Would you rather a toy's vibration be", "category": "spicy",
     "option_a": "Constant and steady", "emoji_a": "🔋",
     "option_b": "Pulsing and unpredictable", "emoji_b": "⚡"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Use a toy on yourself while your partner watches", "emoji_a": "👀",
     "option_b": "Only ever have your partner use it on you", "emoji_b": "🤲"},
    {"prompt": "Would you rather, with something you filmed,", "category": "spicy",
     "option_a": "Delete it right after watching together", "emoji_a": "🗑️",
     "option_b": "Keep it saved somewhere private, just in case", "emoji_b": "🔒"},
    {"prompt": "Would you rather be filmed", "category": "spicy",
     "option_a": "Candid, not posing for it", "emoji_a": "📸",
     "option_b": "Posed, deliberately performing for the camera", "emoji_b": "🎬"},
    {"prompt": "Would you rather", "category": "spicy",
     "option_a": "Control the camera yourself", "emoji_a": "🎥",
     "option_b": "Let your partner control it", "emoji_b": "🕹️"},
    {"prompt": "Would you rather, on camera,", "category": "spicy",
     "option_a": "Keep your face in frame", "emoji_a": "🙂",
     "option_b": "Keep your face out of frame", "emoji_b": "🙈"},
    {"prompt": "Would you rather film with", "category": "spicy",
     "option_a": "Sound on, everything captured", "emoji_a": "🔊",
     "option_b": "Sound off, video only", "emoji_b": "🔇"},
    {"prompt": "Would you rather have sex in", "category": "spicy",
     "option_a": "The car", "emoji_a": "🚗",
     "option_b": "The shower", "emoji_b": "🚿"},
    {"prompt": "Would you rather, before anything starts,", "category": "spicy",
     "option_a": "Be given exact instructions on how to undress", "emoji_a": "📋",
     "option_b": "Be left to decide for yourself how it unfolds", "emoji_b": "🎲"},
    {"prompt": "Would you rather a massage", "category": "spicy",
     "option_a": "Turn rough partway through", "emoji_a": "🔥",
     "option_b": "Stay gentle the whole way through", "emoji_b": "🌸"},
    {"prompt": "Would you rather share a fantasy by", "category": "spicy",
     "option_a": "Describing it out loud in detail first", "emoji_a": "🗣️",
     "option_b": "Just acting it out, no explanation first", "emoji_b": "🎭"},
    {"prompt": "Would you rather be gripped by", "category": "spicy",
     "option_a": "The hips, hard enough to guide the rhythm", "emoji_a": "🤏",
     "option_b": "The shoulders, held down firmly", "emoji_b": "💪"},
    {"prompt": "Would you rather, during rough sex, be called", "category": "spicy",
     "option_a": "By your name", "emoji_a": "🗣️",
     "option_b": "By a pet name or nickname", "emoji_b": "🥰"},
    {"prompt": "Would you rather rough sex", "category": "spicy",
     "option_a": "Start with aggressive kissing first", "emoji_a": "💋",
     "option_b": "Skip kissing, straight to it", "emoji_b": "⚡"},
    {"prompt": "Would you rather be spanked on", "category": "spicy",
     "option_a": "Just the ass", "emoji_a": "🍑",
     "option_b": "The ass and thighs both", "emoji_b": "🔥"},
    {"prompt": "Would you rather do anal", "category": "spicy",
     "option_a": "Bent over furniture", "emoji_a": "🪑",
     "option_b": "Kneeling on the bed", "emoji_b": "🛏️"},
    {"prompt": "Would you rather be edged", "category": "spicy",
     "option_a": "Right to the edge, over and over", "emoji_a": "🔁",
     "option_b": "Just once, then allowed to finish", "emoji_b": "🏁"},
]
