"""
The Would You Rather content bank. Seeded directly into ActivityContent
(activity_type="would_you_rather") - there's no legacy-system equivalent
to migrate from, this game only ever exists in the new Activity system.

Each entry: prompt (shown above both options), category (normal/funny/deep),
option_a/option_b (the two choices), and optional emoji_a/emoji_b for a
little visual flair on each option card.
"""

WOULD_YOU_RATHER_QUESTIONS = []

# --------------------------------------------------------------- Normal
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Spend a week on a tropical island", "emoji_a": "🏝️",
     "option_b": "Spend a week in the mountains", "emoji_b": "🏔️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A home-cooked candlelit dinner", "emoji_a": "🍝",
     "option_b": "A fancy night out at a restaurant", "emoji_b": "🥂"},
    {"prompt": "Would you rather go on", "category": "normal",
     "option_a": "A big trip with friends", "emoji_a": "👯",
     "option_b": "A quiet getaway just the two of us", "emoji_b": "💕"},
    {"prompt": "Would you rather we", "category": "normal",
     "option_a": "Wake up early together", "emoji_a": "🌅",
     "option_b": "Sleep in together", "emoji_b": "😴"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A spontaneous surprise trip", "emoji_a": "🎒",
     "option_b": "A carefully planned dream vacation", "emoji_b": "🗺️"},
    {"prompt": "Would you rather live in", "category": "normal",
     "option_a": "The city", "emoji_a": "🏙️",
     "option_b": "The countryside", "emoji_b": "🌾"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A movie night at home", "emoji_a": "🛋️",
     "option_b": "A night out at the cinema", "emoji_b": "🎬"},
    {"prompt": "Would you rather", "category": "normal",
     "option_a": "Cook a meal together", "emoji_a": "👩‍🍳",
     "option_b": "Order in and relax", "emoji_b": "🥡"},
    {"prompt": "Would you rather take", "category": "normal",
     "option_a": "A road trip", "emoji_a": "🚗",
     "option_b": "A flight somewhere far away", "emoji_b": "✈️"},
    {"prompt": "Would you rather have", "category": "normal",
     "option_a": "A big birthday party", "emoji_a": "🎉",
     "option_b": "A quiet birthday just for two", "emoji_b": "🕯️"},
    {"prompt": "Would you rather stay in", "category": "normal",
     "option_a": "A beach house", "emoji_a": "🏖️",
     "option_b": "A cabin in the woods", "emoji_b": "🛖"},
    {"prompt": "Would you rather save up for", "category": "normal",
     "option_a": "A house", "emoji_a": "🏡",
     "option_b": "A year of travel", "emoji_b": "🧳"},
]

# ---------------------------------------------------------------- Funny
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Only communicate in memes for a week", "emoji_a": "😂",
     "option_b": "Only communicate in song lyrics for a week", "emoji_b": "🎤"},
    {"prompt": "Would you rather fight", "category": "funny",
     "option_a": "One horse-sized duck", "emoji_a": "🦆",
     "option_b": "A hundred duck-sized horses", "emoji_b": "🐴"},
    {"prompt": "Would you rather", "category": "funny",
     "option_a": "Have to sing instead of talk, forever", "emoji_a": "🎶",
     "option_b": "Have to dance instead of walk, forever", "emoji_b": "💃"},
    {"prompt": "Would you rather never eat", "category": "funny",
     "option_a": "Pizza again", "emoji_a": "🍕",
     "option_b": "Another movie night snack again", "emoji_b": "🍿"},
    {"prompt": "Would you rather be able to talk to", "category": "funny",
     "option_a": "Animals", "emoji_a": "🐶",
     "option_b": "Plants", "emoji_b": "🌱"},
    {"prompt": "Would you rather have to", "category": "funny",
     "option_a": "Wear a costume every day for a month", "emoji_a": "🦸",
     "option_b": "Speak in an accent every day for a month", "emoji_b": "🗣️"},
    {"prompt": "Would you rather time travel to", "category": "funny",
     "option_a": "The past", "emoji_a": "⏪",
     "option_b": "The future", "emoji_b": "⏩"},
    {"prompt": "Would you rather I become a famous", "category": "funny",
     "option_a": "Chef", "emoji_a": "👨‍🍳",
     "option_b": "Musician", "emoji_b": "🎸"},
    {"prompt": "Would you rather have", "category": "funny",
     "option_a": "Unlimited snacks but no naps", "emoji_a": "🍪",
     "option_b": "Unlimited naps but no snacks", "emoji_b": "😴"},
    {"prompt": "Would you rather accidentally send an embarrassing text to", "category": "funny",
     "option_a": "Your boss", "emoji_a": "📱",
     "option_b": "Your ex", "emoji_b": "😬"},
]

# ----------------------------------------------------------------- Deep
WOULD_YOU_RATHER_QUESTIONS += [
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always know the full truth, even when it hurts", "emoji_a": "🔍",
     "option_b": "Sometimes be shielded from hard truths", "emoji_b": "🛡️"},
    {"prompt": "Would you rather have more", "category": "deep",
     "option_a": "Time", "emoji_a": "⏳",
     "option_b": "Money", "emoji_b": "💰"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Understood a little by everyone", "emoji_a": "🌍",
     "option_b": "Deeply understood by just one person", "emoji_b": "❤️"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Never fight again", "emoji_a": "🕊️",
     "option_b": "Always resolve every fight perfectly", "emoji_b": "🤝"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Relive your favourite memory forever", "emoji_a": "🔁",
     "option_b": "Keep making new ones, even if they fade", "emoji_b": "✨"},
    {"prompt": "Would you rather be", "category": "deep",
     "option_a": "Fearless", "emoji_a": "🦁",
     "option_b": "Endlessly patient", "emoji_b": "🧘"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Know exactly how your story ends", "emoji_a": "📖",
     "option_b": "Be surprised by every twist", "emoji_b": "❓"},
    {"prompt": "Would you rather give up", "category": "deep",
     "option_a": "Your phone for a year", "emoji_a": "📵",
     "option_b": "Caffeine for a year", "emoji_b": "☕"},
    {"prompt": "Would you rather", "category": "deep",
     "option_a": "Always speak your mind", "emoji_a": "🗯️",
     "option_b": "Always keep the peace", "emoji_b": "🤫"},
    {"prompt": "Would you rather have", "category": "deep",
     "option_a": "One big, unforgettable adventure", "emoji_a": "🏔️",
     "option_b": "Many small, quiet ones", "emoji_b": "🌤️"},
]
