"""add appreciations table

Revision ID: 08b94fbad20d
Revises: 1143e1e7ce1d
Create Date: 2026-09-06 09:43:59.908209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b94fbad20d'
down_revision = '1143e1e7ce1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appreciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=500), nullable=False),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_kept', sa.Boolean(), nullable=False),
    sa.Column('reaction_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appreciations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appreciations_couple_id'), ['couple_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appreciations_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appreciations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appreciations_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_appreciations_couple_id'))

    op.drop_table('appreciations')
    # ### end Alembic commands ###
