"""add 20 Questions dedicated turn-based tables

Revision ID: 0b87df20f1e6
Revises: 3f0f07f72488
Create Date: 2026-09-04 06:41:46.555258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b87df20f1e6'
down_revision = '3f0f07f72488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twenty_questions_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('chooser_user_id', sa.Integer(), nullable=False),
    sa.Column('guesser_user_id', sa.Integer(), nullable=False),
    sa.Column('secret_category', sa.String(length=16), nullable=False),
    sa.Column('secret_text', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chooser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['guesser_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twenty_questions_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twenty_questions_games_couple_id'), ['couple_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_twenty_questions_games_status'), ['status'], unique=False)

    op.create_table('twenty_questions_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=300), nullable=False),
    sa.Column('is_guess', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.String(length=16), nullable=True),
    sa.Column('asked_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['twenty_questions_games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'turn_number', name='uq_20q_game_turn_number')
    )
    with op.batch_alter_table('twenty_questions_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twenty_questions_turns_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_questions_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twenty_questions_turns_game_id'))

    op.drop_table('twenty_questions_turns')
    with op.batch_alter_table('twenty_questions_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twenty_questions_games_status'))
        batch_op.drop_index(batch_op.f('ix_twenty_questions_games_couple_id'))

    op.drop_table('twenty_questions_games')
    # ### end Alembic commands ###
