"""add couple_challenges for the Challenges feature

Revision ID: 1143e1e7ce1d
Revises: 0b87df20f1e6
Create Date: 2026-09-05 17:25:43.433551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1143e1e7ce1d'
down_revision = '0b87df20f1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requires_both', sa.Boolean(), nullable=False),
    sa.Column('completed_by_json', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['activity_contents.id'], ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_id', 'content_id', name='uq_couple_challenge_content')
    )
    with op.batch_alter_table('couple_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couple_challenges_couple_id'), ['couple_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couple_challenges_couple_id'))

    op.drop_table('couple_challenges')
    # ### end Alembic commands ###
