"""add activity_daily_selections for architectural integration phase

Revision ID: 3f0f07f72488
Revises: 421c0bed5e2b
Create Date: 2026-09-01 23:10:22.085900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0f07f72488'
down_revision = '421c0bed5e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_daily_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['activity_contents.id'], ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_id', 'date', name='uq_activity_daily_couple_date')
    )
    with op.batch_alter_table('activity_daily_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_daily_selections_couple_id'), ['couple_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_daily_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_daily_selections_couple_id'))

    op.drop_table('activity_daily_selections')
    # ### end Alembic commands ###
