"""add reusable activity system (Activity, ActivityContent, ActivitySubmission, ActivityResult)

Revision ID: 421c0bed5e2b
Revises: fc33a6286a70
Create Date: 2026-09-01 06:05:21.152496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421c0bed5e2b'
down_revision = 'fc33a6286a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('spicy_level', sa.Integer(), nullable=True),
    sa.Column('match_eligible', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_contents_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_contents_category'), ['category'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['activity_contents.id'], ),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_couple_id'), ['couple_id'], unique=False)

    op.create_table('activity_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('is_competitive', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('points_json', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_results_activity_id'), ['activity_id'], unique=True)

    op.create_table('activity_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_activity_submission_user')
    )
    with op.batch_alter_table('activity_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_submissions_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_submissions_activity_id'))

    op.drop_table('activity_submissions')
    with op.batch_alter_table('activity_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_results_activity_id'))

    op.drop_table('activity_results')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_couple_id'))
        batch_op.drop_index(batch_op.f('ix_activities_content_id'))

    op.drop_table('activities')
    with op.batch_alter_table('activity_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_contents_category'))
        batch_op.drop_index(batch_op.f('ix_activity_contents_activity_type'))

    op.drop_table('activity_contents')
    # ### end Alembic commands ###
