"""add challenge cycle tracking and skip status

Revision ID: 83890191659b
Revises: 7d1ec157c75f
Create Date: 2026-09-19 12:40:37.239003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83890191659b'
down_revision = '7d1ec157c75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple_challenge_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couple_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('current_cycle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_id', 'category', name='uq_couple_challenge_cycle_category')
    )
    with op.batch_alter_table('couple_challenge_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couple_challenge_cycles_couple_id'), ['couple_id'], unique=False)

    with op.batch_alter_table('couple_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle', sa.Integer(), server_default='1', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_couple_challenge_content'), type_='unique')
        batch_op.create_unique_constraint('uq_couple_challenge_content_cycle', ['couple_id', 'content_id', 'cycle'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couple_challenges', schema=None) as batch_op:
        batch_op.drop_constraint('uq_couple_challenge_content_cycle', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_couple_challenge_content'), ['couple_id', 'content_id'])
        batch_op.drop_column('cycle')

    with op.batch_alter_table('couple_challenge_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couple_challenge_cycles_couple_id'))

    op.drop_table('couple_challenge_cycles')
    # ### end Alembic commands ###
